### ISSUE TITLE
env error

### ISSUE THREAD

**Issue by ltm920716** [Oneflow-Inc/diffusers#10]
### Describe the bug

docker image: oneflowinc/oneflow-sd:cu112

nvcc -V 

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

cuda version does not match!!

### Reproduction

0

### Logs

```shell
0
```

### System Info

0

**Comment by jackalcooper** [comment]
what is your full command of `docker run`?

**Comment by ltm920716** [comment]
@jackalcooper 
docker pull oneflowinc/oneflow-sd:cu112

I pull the tag cu112, but in the the container the version of cuda is 11.8

**Comment by jackalcooper** [comment]
> I pull the tag cu112, but in the the container the version of cuda is 11.8

this should work. They are compatible with each other.

**Comment by shangguanshiyuan** [comment]
Thanks for your feedback. This issue will be closed. If you have any other questions, you can reopen this or open a new issue at any time.
