### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'net' - Custom Stable Diffusion Pipeline

### ISSUE THREAD

**Issue by chavinlo** [Oneflow-Inc/diffusers#102]
Hello, I am trying to replicate the work of the Stable Diffusion Pipeline so I can have more control over it.
More specifically, I want to only load specific (compiled) Unets and VAEs.

To do this I've written the following script:

https://gist.github.com/chavinlo/79776f50006698e477796c4c58083623

Everything goes well until inference on the unet is attempted, more precisely at L248: https://gist.github.com/chavinlo/79776f50006698e477796c4c58083623#file-test-py-L248

The model thinks its not compiled and tries to compile it, and returns the following error:

```python
Traceback (most recent call last):
  File "/root/node/test_the_test.py", line 5, in <module>
    engine(json.load(open('/root/node/cfg/basic.json')))
  File "/root/env/lib/python3.10/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/root/node/test.py", line 248, in engine
    noise_pred = unet_graph(latent_model_input, t, text_embeddings)
  File "/root/diffusers/src/diffusers/oneflow_graph_compile_cache.py", line 61, in __call__
    self.compile(*args, **kwargs)
  File "/root/diffusers/src/diffusers/oneflow_graph_compile_cache.py", line 31, in compile
    self.graph_._compile_from_shared(*args, **kwargs)
  File "/root/env/lib/python3.10/site-packages/oneflow/nn/graph/graph.py", line 872, in _compile_from_shared
    self._shared_graph._forward_job_proto.net.op
AttributeError: 'NoneType' object has no attribute 'net'
```

its trying to use _graph, that object seems to have the net attribute along with the rest that it's looking for
but the script searches it up as "_shared_graph"

![image](https://user-images.githubusercontent.com/85657083/219280512-bddfcdf1-9561-4bab-80a2-201ccfcb6c27.png)

What it's looking for:
![image](https://user-images.githubusercontent.com/85657083/219280576-f9d31ae1-f5cf-49c1-bff9-5ed24cba05a6.png)

right is the line where it breaks and left is the graph_ object above

![image](https://user-images.githubusercontent.com/85657083/219280598-ddbe02b8-37d9-4905-acc7-6f233205416b.png)
![image](https://user-images.githubusercontent.com/85657083/219280647-d1166805-ced1-448a-af27-0ceb0df083d4.png)

![image](https://user-images.githubusercontent.com/85657083/219280742-0cc7e202-c97a-4f0b-b4d9-4db91baaeb42.png)

So first when unet_graph() is called graph_.forward_job_proto is None
but at the end of it self._shared_graph is None and the prior graph_ is Attr Error
Then _compile_from_shared is called again? this time self.graph_ is net
Then everything turns in to namerror where self is not defined and unet_graph is called again?
and then it fails with graph_ being net and _shared_graph being attr error

This is the lpw.py code if needed:
https://gist.github.com/chavinlo/9e4c5c6c8e0f82f882a04a3fe4e54d88
note that it's different from the other issue I created

Any suggestions?

**Comment by strint** [comment]
It seems that you only want to use unet graph. So you don't need the OneFlowGraphCompileCache, because you create a unet_map by yourself.

You can use API on nn.Graph to get your job done.

## Usage
### Multiple graph sharing
````
linear_g_0.enable_shared()
linear_g_1. share_from(linear_g_0)
````
### graph saving and loading
save
```
linear_g.enable_save_runtime_state_dict()
state_dict = linear_g.runtime_state_dict()
flow. save(state_dict, filename)
```
load
```
state_dict = flow. load(filename)
linear_g.load_runtime_state_dict(state_dict)
```



Reference this linear graph example:
- full example of share/save/load: https://github.com/Oneflow-Inc/oneflow/blob/e3737549ebcaa05d1e2e953ec5f44af3e97e3e4f/python/oneflow/test/expensive/test_graph_multi_graph.py#L325
- graph load and share:https://github.com/Oneflow-Inc/oneflow/blob/e3737549ebcaa05d1e2e953ec5f44af3e97e3e4f/python/oneflow/test/expensive/test_graph_multi_graph.py#L217

**Comment by chavinlo** [comment]
Will this work even if multiple resolutions are wanted?

**Comment by strint** [comment]
> Will this work even if multiple resolutions are wanted?

Yes, OneFlowGraphCompileCache is built on the nn.Graph.

**Comment by jackalcooper** [comment]
looks like it has been resolved, feel free to reopen if not.
