### ISSUE TITLE
无法找到OneFlowStableDiffusionPipeline

### ISSUE THREAD

**Issue by gaodianzhuo** [Oneflow-Inc/diffusers#103]
### Describe the bug

Python 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.6.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from diffusers import OneFlowStableDiffusionPipeline
╭───────────────────────────── Traceback (most recent call last) ──────────────────────────────╮
│ <ipython-input-1-e1ab94322590>:1 in <module>                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'OneFlowStableDiffusionPipeline' from 'diffusers' 
(/home/arthur/miniconda3/envs/dd/lib/python3.10/site-packages/diffusers/__init__.py)

In [2]: import diffusers

In [3]: diffusers.__version__
Out[3]: '0.12.1'

In [4]: 

### System Info

diffusers 0.12.1
ubuntu 20.04

**Comment by Alokia** [comment]
可以先按照 https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#without-docker 进行配置，然后按照 #104 的办法尝试解决

**Comment by gaodianzhuo** [comment]
还是报同样的错误无法解决
In [1]: from transformers import CLIPTextModel, CLIPFeatureExtractor

In [2]: import diffusers

In [3]: from diffusers import OneFlowStableDiffusionPipeline
╭───────────────────────────── Traceback (most recent call last) ──────────────────────────────╮
│ <ipython-input-3-e1ab94322590>:1 in <module>                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'OneFlowStableDiffusionPipeline' from 'diffusers' 
(/home/arthur/miniconda3/envs/dd/lib/python3.10/site-packages/diffusers/__init__.py)

In [4]:

**Comment by strint** [comment]
```
ImportError: cannot import name 'OneFlowStableDiffusionPipeline' from 'diffusers'
(/home/arthur/miniconda3/envs/dd/lib/python3.10/site-packages/diffusers/init.py)
```

你使用的 diffusers 看起来是官方的，而不是 oneflow 的吧

**Comment by Alokia** [comment]
这问题我也遇到了，但是不知道为什么后面就没了，变成 #104 这个问题了。我记得我把要下载的库删了，重新按照 https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#without-docker 走了一遍

**Comment by Alokia** [comment]
你的 diffusers 版本是0.12，应该不是oneflow的，卸载后用源码安装 
```
git clone https://github.com/Oneflow-Inc/diffusers.git
cd diffusers
python3 -m pip install -e .[oneflow]
```

**Comment by jackalcooper** [comment]
please check out the new non-fork implementation, wiki has been update at https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion
