### ISSUE TITLE
我用的非docker安装的环境，生成的结果看着很不对

### ISSUE THREAD

**Issue by dingjingzhen** [Oneflow-Inc/diffusers#11]
### Describe the bug

![image](https://user-images.githubusercontent.com/21244263/200337208-bf493b32-f6e3-461c-b44b-314566668bbd.png)
![image](https://user-images.githubusercontent.com/21244263/200337353-7769f61a-d4aa-4f08-819d-61133828b279.png)
![image](https://user-images.githubusercontent.com/21244263/200337383-78edfb3d-d797-4bac-9e6a-bc199746db89.png)
这些生成结果明显就很有问题，和huggingface diffuser的结果不太一样，是我哪里搞得不对吗？

### Reproduction

import oneflow as torch
import time
from diffusers import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=torch.float16,
)

pipe = pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"

for i in range(10):
    torch.cuda.synchronize()
    sampler_time = time.time()
    with torch.autocast("cuda"):
        images = pipe(prompt).images
    torch.cuda.synchronize()
    sampler1_time = time.time()
    print('loop_time:',sampler1_time-sampler_time)  
    for j, image in enumerate(images):
        image.save(f"{prompt}-of-{j}-{i}.png")

### System Info

diffusers-0.4.0.dev0
transformers-4.23.0.dev0
python3.8.13
pytorch 1.13.0a0+d0d6b1f
cuda11,8

**Comment by jackalcooper** [comment]
可能是因为我们支持的diffusers版本较旧，之后会升级到最新的版本，在效果方面会有所提升。

**Comment by dingjingzhen** [comment]
> 可能是因为我们支持的diffusers版本较旧，之后会升级到最新的版本，在效果方面会有所提升。

哦哦，感谢回复，我试了下生成的速度确实得到了非常大的提升，如果生成效果完全和原始的一模一样将是个非常非常棒的工作。冒昧的问一下，你们大概什么时候能支持最新的diffusers呢，我希望能成为第一批使用的人

**Comment by jackalcooper** [comment]
> 我希望能成为第一批使用的人

到时候会告诉你～

**Comment by dingjingzhen** [comment]
> 我试了下docker好像生成结果也不大对 #14

给我的回复是因为用的老的diffusers，老版本的我没有用过，不知道是不是有这个问题，oneflow理论上是框架或者编译器层面的优化，属于工程层面的加速，不涉及算法本身，效果应该和原始模型出来的结果一模一样，后续看更新后会不会变好

**Comment by zyx1213271098** [comment]
batch sise只能设为1吗？我设置batch size = 3，就报错了。

**Comment by jackalcooper** [comment]
> batch sise只能设为1吗？我设置batch size = 3，就报错了（非docker版本）。 The excepted tensor meta is: shape=(2,4,64,64), dtype=oneflow.float32, device=cuda:0, but the actual tensor meta is: shape=(6,4,64,64), dtype=oneflow.float32, device=cuda:

这个是在哪里设置的呢

**Comment by zyx1213271098** [comment]
> > batch sise只能设为1吗？我设置batch size = 3，就报错了（非docker版本）。 The excepted tensor meta is: shape=(2,4,64,64), dtype=oneflow.float32, device=cuda:0, but the actual tensor meta is: shape=(6,4,64,64), dtype=oneflow.float32, device=cuda:
> 
> 这个是在哪里设置的呢

[prompt] *3

**Comment by jackalcooper** [comment]
@zyx1213271098 could you post your full script?

**Comment by zyx1213271098** [comment]
> @zyx1213271098 could you post your full script?

sorry，发现问题了。因为前面模型跑过batch size=1的前向，就不可以跑其他batch size的了

**Comment by jackalcooper** [comment]
应该有所改善，请再试试看

**Comment by dingjingzhen** [comment]
> 应该有所改善，请再试试看

感谢，我想问下你们目前的这个改善，是已经和diffusers的生成结果是一模一样了吗？还是说还是会有细微差距，因为我的理解是oneflow应该是编译器或者框架层面的加速，应该不影响算法效果

**Comment by dingjingzhen** [comment]
> 应该有所改善，请再试试看

刚刚试了下，确实好很多，但是我不确定跟目前最新的diffusers还有没有区别，可以的话空闲的时候麻烦告知一下，确定没有问题，我就尝试直接用起来了

**Comment by zyx1213271098** [comment]
确实好很多，但感觉生成的图片语义上有些问题。比如我prompt里面有“computer desktop wallpaper”修饰，真的就会生成一张电脑+壁纸的结果，是不是text embedding的精度不太够？

**Comment by jackalcooper** [comment]
> > 应该有所改善，请再试试看
> 
> 刚刚试了下，确实好很多，但是我不确定跟目前最新的diffusers还有没有区别，可以的话空闲的时候麻烦告知一下，确定没有问题，我就尝试直接用起来了

好的我再看看

**Comment by jackalcooper** [comment]
> > 应该有所改善，请再试试看
> 
> 刚刚试了下，确实好很多，但是我不确定跟目前最新的diffusers还有没有区别，可以的话空闲的时候麻烦告知一下，确定没有问题，我就尝试直接用起来了

还没有完全合并最新的huggingface

**Comment by jackalcooper** [comment]
@dingjingzhen 在 oneflow-fork 分支又合并了一些上游新的改动，应该效果又会好了些

**Comment by jackalcooper** [comment]
```python
dpm_solver = DPMSolverMultistepScheduler.from_config("CompVis/stable-diffusion-v1-4", subfolder="scheduler")

model = "CompVis/stable-diffusion-v1-4"
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model,
    use_auth_token=True,
    revision="fp16",
    torch_dtype=torch.float16,
    scheduler=dpm_solver
)
```
也可以考虑用这个schduler，20步就能出不错的图

**Comment by dingjingzhen** [comment]
> ```python
> ```python
> from diffusers import OneFlowDPMSolverMultistepScheduler as DPMSolverMultistepScheduler
> dpm_solver = DPMSolverMultistepScheduler.from_config("CompVis/stable-diffusion-v1-4", subfolder="scheduler")
> 
> model = "CompVis/stable-diffusion-v1-4"
> pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>     model,
>     use_auth_token=True,
>     revision="fp16",
>     torch_dtype=torch.float16,
>     scheduler=dpm_solver
> )
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 也可以考虑用这个schduler，20步就能出不错的图
> ```

嗯，这个作者我认识，已经用上了，如果再加上你们这个，那就极其厉害了
