### ISSUE TITLE
dev confusion

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#135]
Hi, I'm confused between `main` and `oneflow-fork` branches which is suppose to be the one I can use for reference?

**Comment by Ldpe2G** [comment]
The `oneflow-fork` branch is deprecated. you should use the `main` branch.

**Comment by NicholasKao1029** [comment]
thanks @Ldpe2G, how about the tests in the `oneflow-fork`.
Specifically looking at https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture

**Comment by Nipi64310** [comment]
> The `oneflow-fork` branch is deprecated. you should use the `main` branch.

Hi @Ldpe2G ，
Why does the main branch lack the OneFlowStableDiffusionImg2ImgPipeline class?

**Comment by Ldpe2G** [comment]
> thanks @Ldpe2G, how about the tests in the `oneflow-fork`. Specifically looking at https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture

> Hi @Ldpe2G ， Why does the main branch lack the OneFlowStableDiffusionImg2ImgPipeline class?

we are working on move these to `main` branch. @NicholasKao1029 @Nipi64310

**Comment by strint** [comment]
> thanks @Ldpe2G, how about the tests in the `oneflow-fork`. Specifically looking at https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture

You can try this test in PR: https://github.com/Oneflow-Inc/diffusers/pull/137

**Comment by NicholasKao1029** [comment]
I see I see, thanks for speedy replies @Ldpe2G @strint

**Comment by strint** [comment]
> thanks @Ldpe2G, how about the tests in the `oneflow-fork`. Specifically looking at https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture

The update has been merged, https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture

**Comment by NicholasKao1029** [comment]
Ill close issue since my original question has been answered
