### ISSUE TITLE
Numpy warning

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#141]
```
/opt/conda/lib/python3.8/site-packages/torch/_utils.py:146: UserWarning: Failed to initialize NumPy: module compiled against API version 0xf but this version of numpy is 0xd (Triggered internally at /opt/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:77.)
```
Numpy error when running https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py just a warning but would like to understand as I am using docker container `oneflow/onediff:cu117`

**Comment by Hank0626** [comment]
I believe this is highly likely due to the incompatibility between your `NumPy` version and `PyTorch` version.
You can try to use
```
pip install --upgrade numpy
```
to upgrade your `numpy` version and try it again.
