### ISSUE TITLE
Onediff interoperability with diffusers

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#143]
Is this project meant to be interoperable with diffusers? 
as in the `pipe` created from `onediff` can use features from `diffusers`, or does this have to continue to develop alongside `diffusers` when new features come out?

**Comment by jackalcooper** [comment]
> does this have to continue to develop alongside `diffusers` when new features come out?

Yes, we intend to support features introduced in diffusers in the future. Some need a dedicated module(pipes) while some don't (most of schedulers, text encoders)
