### ISSUE TITLE
enable_attention_slicing的作用

### ISSUE THREAD

**Issue by baymin0220** [Oneflow-Inc/diffusers#145]
您好，这个enable_attention_slicing是没有发挥作用的吗？看到加了这个以后内存没有特别明显的变化。

**Comment by jackalcooper** [comment]
按理说是有变化的，可以试试看运行 benchmarks/stable_diffusion_v1_5_unet.py，里面 unet 调用 `set_attention_slice`。这样排除一些干扰

**Comment by jackalcooper** [comment]
Slice | VRAM | Thoughput
-- | -- | --
auto | 3979MiB | 12.66it/s
None | 3841MiB | 18.53it/s
