### ISSUE TITLE
Upcsale pipeline 

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#149]
Do you guys remove the `StableDiffusionLatentUpscalePipeline` or modify the `/opt/conda/lib/python3.8/site-packages/diffusers/__init__.py` for diffusers in your `oneflowinc/onediff:cu117`?

this is within the python repl
```
root@36232372c699:/workspace# python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:10)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from diffusers import StableDiffusionLatentUpscalePipeline, StableDiffusionPipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'StableDiffusionLatentUpscalePipeline' from 'diffusers' (/opt/conda/lib/python3.8/site-packages/diffusers/__init__.py)
>>>
```

i'm on diffusers>0.12 and can actually find the specific file via the conda path of the upscaler https://github.com/huggingface/diffusers/blob/v0.12.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py#L54 in the container.

confused!

**Comment by Hank0626** [comment]
I think it's name is `StableDiffusionUpscalePipeline`? in your [link](https://github.com/huggingface/diffusers/blob/v0.12.0/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_upscale.py#L54)
Maybe you should modify to
```
from diffusers import StableDiffusionUpscalePipeline, StableDiffusionPipeline
```

**Comment by NicholasKao1029** [comment]
ahhh you are correct. I copied the test script from HF documentation but didn't verify thank you @Hank0626
