### ISSUE TITLE
请问 Oneflow 和 AITemplate 在stable diffusion text2img / img2img上的benchmark对比有吗？

### ISSUE THREAD

**Issue by lizhengwei1992** [Oneflow-Inc/diffusers#158]
例如：https://github.com/facebookincubator/AITemplate/tree/main/examples/05_stable_diffusion

**Comment by Hank0626** [comment]
Currently, we do not have a benchmark comparison between Oneflow and AITemplate for stable diffusion text2img / img2img. However, we appreciate your suggestion and will consider adding this comparison in future updates. Please stay tuned.

**Comment by Hank0626** [comment]
Please refer to https://zhuanlan.zhihu.com/p/581965314
