### ISSUE TITLE
TypeError: enable.__init__() got an unexpected keyword argument 'lazy'

### ISSUE THREAD

**Issue by ChinaGPT** [Oneflow-Inc/diffusers#159]
(huatu) m@m-70FRR00CCN:~/onediff$ python3 examples/text_to_image.py
Traceback (most recent call last):
  File "/home/m/onediff/examples/text_to_image.py", line 4, in <module>
    from onediff import OneFlowStableDiffusionPipeline
  File "/home/m/onediff/src/onediff/__init__.py", line 20, in <module>
    flow.mock_torch.enable(lazy= True)
TypeError: enable.__init__() got an unexpected keyword argument 'lazy'

**Comment by Hank0626** [comment]
Could you please give your oneflow version bu typing:
```
python3 -m oneflow --doctor
```

**Comment by ChinaGPT** [comment]
version: 0.9.0+cu117

**Comment by Hank0626** [comment]
https://github.com/Oneflow-Inc/oneflow/blob/8fce5534487bb86a8683544f5f55ca52d6ae915f/python/oneflow/mock_torch/__init__.py#L235
I think in v0.9.0 `flow.mock_torch.enable` already has the `lazy` args

**Comment by jackalcooper** [comment]
Please try upgrade oneflow to latest nightly version with
```
python3 -m pip install -U --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
```
