### ISSUE TITLE
无法运行demo的报错

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#178]
如果按照wiki运行docker会提示：
![4dfec8a0502b33745a7ad11a80e284c](https://user-images.githubusercontent.com/96160062/230846338-62754e32-1b66-4b23-b25e-2154677c21bc.png)

**Comment by Hank0626** [comment]
刚刚已经更新了docker的版本（更新了diffusers的版本依赖），可以pull最新的版本再试试看

**Comment by sanbuphy** [comment]
感谢
