### ISSUE TITLE
pip install accelerate 安装后跑benchmark报错

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#179]
我在尝试benchmark的时候遇到了这个提示：
```text
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to 

`low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model 

loading. You can do so with: 

pip install accelerate

```

根据提示安装后在运行会出现这样的问题：
![2023-04-10 15-11-41 的屏幕截图](https://user-images.githubusercontent.com/96160062/230847731-371fef98-9a50-4f77-b737-96725dcde85c.png)
请问该如何解决呢，感谢

**Comment by Hank0626** [comment]
请问你跑的是哪个文件呢？

**Comment by sanbuphy** [comment]
> 请问你跑的是哪个文件呢？

你好，[stable_diffusion_2_unet.py](https://github.com/Oneflow-Inc/diffusers/blob/main/benchmarks/stable_diffusion_2_unet.py)  和另外一个文件都会报错，如果不安装的话就不报错

**Comment by Hank0626** [comment]
* 先确认下你的环境中已经没有accelerate模块，如果还有的话，执行
```
python3 -m pip uninstall accelerate -y
```

* 如果以上还不行的话把这里https://github.com/Oneflow-Inc/diffusers/blob/8b11f10adfbe6fafc382cc31e4b4da7c754cc933/benchmarks/stable_diffusion_2_unet.py#L22 改成
```
flow.mock_torch.enable(lazy=True)
```
再试一下看看

**Comment by sanbuphy** [comment]
> * 先确认下你的环境中已经没有accelerate模块，如果还有的话，执行
> 
> ```
> python3 -m pip uninstall accelerate -y
> ```
> 
> * 如果以上还不行的话把这里https://github.com/Oneflow-Inc/diffusers/blob/8b11f10adfbe6fafc382cc31e4b4da7c754cc933/benchmarks/stable_diffusion_2_unet.py#L22
>    改成
> 
> ```
> flow.mock_torch.enable(lazy=True)
> ```
> 
> 再试一下看看

你好，已经没有的话是可以运行的，但我很好奇这个到底是不是需要的

**Comment by Hank0626** [comment]
这是不需要的，因为oneflow没有适配原本diffusers的accelerate加速模块，所以需要卸载，在[Readme](https://github.com/Oneflow-Inc/diffusers/blob/main/README.md)中也有相应的instruction。

**Comment by sanbuphy** [comment]
> 

好的 谢谢
