### ISSUE TITLE
请问如何减少推理前的加载时间？

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#180]
你好，我在推理过程中发现每次真正计算推理（有进度条）之前都需要加载模型到显存，需要很长的时间。
我有什么办法把他服务化——让模型都先加载好，然后我只要请求推理即可。感谢

**Comment by strint** [comment]
提供了一个主要的解法：离线做编译，在线时加载编译结果以省掉编译时间延迟。参考文档：
- Pipeline 上的支持：https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture
- Unet/Vae graph 的支持：https://github.com/Oneflow-Inc/diffusers/wiki/Multi-Graph-Sharing-through-nn.Graph-Dynamic-Input-Shape

**Comment by sanbuphy** [comment]
> 提供了一个主要的解法：离线做编译，在线时加载编译结果以省掉编译时间延迟。参考文档：
> 
> * Pipeline 上的支持：https://github.com/Oneflow-Inc/diffusers/wiki/Optimization-for-Multi-Resolution-Picture
> * Unet/Vae graph 的支持：https://github.com/Oneflow-Inc/diffusers/wiki/Multi-Graph-Sharing-through-nn.Graph-Dynamic-Input-Shape

谢谢你，让我进行一下尝试！
我还想请教一下oneflow的sd能集成到webui中去吗？有人做过这方面的尝试嘛，非常感谢。
