### ISSUE TITLE
请问有显式的api调用推理方式吗？

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#182]
你好，我想请问有没有暴露的api可以执行这两步操作：
model = load_from(xxxxxx) （比如本地编译后的静态图）
result = model.infer(xxxxx)

因为我发现就算进了pipe，还要很长时间才能到正式的推理阶段。。。但是太慢了

![2ae85c5db81624476f1b8bd07c84c55](https://user-images.githubusercontent.com/96160062/230908852-37f83d19-34de-4d99-9e4a-0f1c835e7169.png)
![ae56407db2cb1508429641ed1fd0563](https://user-images.githubusercontent.com/96160062/230908862-c6f3c6f6-7910-4ef5-a570-4331f298d7f7.png)

然后我也不知道要不要对这里显式调优：
![e9c8c6d27d1314d475006e3070d794a](https://user-images.githubusercontent.com/96160062/230908928-48c04703-00fa-48da-9e73-e05e46580588.png)

提前感谢研发大哥。

**Comment by Hank0626** [comment]
* 这是存图的方式
```
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_id,
    revision="fp16",
    torch_dtype=flow.float16,
) # 定义pipe
pipe = pipe.to("cuda")
pipe.set_graph_compile_cache_size(9) #设置图的动态cache大小
pipe.enable_graph_share_mem( ) #启动图的share_mem功能
images = pipe(
    prompt,
    height=image_height,
    width=image_weight,
    compile_unet=True,     # 打开编译unet图的开关
    compile_vae=True,      # 打开编译unet图的开关
).images

pipe.save_pretrained(pipe_file_path)  #存pipe
pipe.save_graph(graph_save_path)  #存编译好的图
```
* 这是读图的方式
```
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    pipe_file_path,
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)

pipe = pipe.to("cuda")
pipe.set_graph_compile_cache_size(9)

pipe.load_graph(graph_save_path, compile_unet=True, compile_vae=True) #读save过程保存的图

images = pipe(
    prompt,
    height=512,
    width=512,
    compile_unet=True,
    compile_vae=True,
).images
```

更加详细的example可以去https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py 这里看看

**Comment by Hank0626** [comment]
不过目前对于vae图的支持好像还有点问题，你可以先选择只把所有的compile_unet设置为True，并设置存图的路径，这样读图之后的推理速度就可以得到很大的改善。

**Comment by sanbuphy** [comment]
> 不过目前对于vae图的支持好像还有点问题，你可以先选择只把所有的compile_unet设置为True，并设置存图的路径，这样读图之后的推理速度就可以得到很大的改善。

感谢！！  但是我想请问从 pipe 到实际上推理过程中，那个漫长的等待时间主要是做什么呢？ 我发现pipe本身都要很久（普通情况下

**Comment by sanbuphy** [comment]
> 不过目前对于vae图的支持好像还有点问题，你可以先选择只把所有的compile_unet设置为True，并设置存图的路径，这样读图之后的推理速度就可以得到很大的改善。

你好，我运行了那个文件，但是遇到了这样的错误：
![2023-04-11 10-04-02 的屏幕截图](https://user-images.githubusercontent.com/96160062/231036553-c2b89943-7128-4b27-a019-400d64005c6f.png)

**Comment by Hank0626** [comment]
这是你显卡显存不足导致的，你把里面的size从1024，调整小一点，一般来说对于12gb显存的gpu，调成512就可以了

**Comment by sanbuphy** [comment]
> 

谢谢，减小size后解决，猜测应该是多论测试申请显存导致的问题（实际上用不到那么多，还剩下很多没用的

**Comment by strint** [comment]
> 从 pipe 到实际上推理过程中，那个漫长的等待时间主要是做什么呢

pipe 的第一次调用，会触发内部 unet 模型的编译优化，这个会耗费8s左右的时间（不同机器可能不太一样）。

**Comment by sanbuphy** [comment]
> @sanbuphy
> 
> * 这是存图的方式
> 
> ```
> pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>     model_id,
>     revision="fp16",
>     torch_dtype=flow.float16,
> ) # 定义pipe
> pipe = pipe.to("cuda")
> pipe.set_graph_compile_cache_size(9) #设置图的动态cache大小
> pipe.enable_graph_share_mem( ) #启动图的share_mem功能
> images = pipe(
>     prompt,
>     height=image_height,
>     width=image_weight,
>     compile_unet=True,     # 打开编译unet图的开关
>     compile_vae=True,      # 打开编译vae图的开关
> ).images
> 
> pipe.save_pretrained(pipe_file_path)  #存pipe
> pipe.save_graph(graph_save_path)  #存编译好的图
> ```
> 
> * 这是读图的方式
> 
> ```
> pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>     pipe_file_path,
>     use_auth_token=True,
>     revision="fp16",
>     torch_dtype=flow.float16,
> )
> 
> pipe = pipe.to("cuda")
> pipe.set_graph_compile_cache_size(9)
> 
> pipe.load_graph(graph_save_path, compile_unet=True, compile_vae=True) #读save过程保存的图
> 
> images = pipe(
>     prompt,
>     height=512,
>     width=512,
>     compile_unet=True,
>     compile_vae=True,
> ).images
> ```
> 
> 更加详细的example可以去https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py 这里看看

你好，我在读图的时候发现这个错误：
![2023-04-11 17-43-48 的屏幕截图](https://user-images.githubusercontent.com/96160062/231121769-263f7a08-61c7-4968-9e99-8f4fcd625c46.png)

**Comment by sanbuphy** [comment]
> > 从 pipe 到实际上推理过程中，那个漫长的等待时间主要是做什么呢
> 
> pipe 的第一次调用，会触发内部 unet 模型的编译优化，这个会耗费8s左右的时间（不同机器可能不太一样）。

get ，谢谢
