### ISSUE TITLE
No module named 'oneflow.utils.checkpoint'

### ISSUE THREAD

**Issue by xiaohaipeng** [Oneflow-Inc/diffusers#19]
### Describe the bug

oneflow 0.8.0 
diffusers               0.4.0.dev0
when i runned OneFlowStableDiffusionPipeline locally ,i met the problem,

/////////////////////
Traceback (most recent call last):
  File "test_of.py", line 2, in <module>
    from diffusers import OneFlowStableDiffusionPipeline
  File "/mnt/yinlong/project/disco/one-flow/diffusers/src/diffusers/__init__.py", line 21, in <module>
    from .models import AutoencoderKL, UNet2DConditionModel, UNet2DModel, VQModel
  File "/mnt/yinlong/project/disco/one-flow/diffusers/src/diffusers/models/__init__.py", line 28, in <module>
    from .unet_2d_condition_oneflow import OneFlowUNet2DConditionModel
  File "/mnt/yinlong/project/disco/one-flow/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 6, in <module>
    import oneflow.utils.checkpoint
ModuleNotFoundError: No module named 'oneflow.utils.checkpoint'
////////////////////////////////////

what is the problem?BUG?

### System Info

the command failed too, met the same question above

**Comment by jackalcooper** [comment]
it doesn't support the version 0.8.0 of oneflow. Please install via 
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112
```

**Comment by xiaohaipeng** [comment]
@jackalcooper oneflow 0.8.1 work,but met AttributeError

############
libibverbs not available, ibv_fork_init skipped
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 14484.97it/s]
[diffusers] [tokenizer] transformers.CLIPTokenizer
ftfy or spacy is not installed using BERT BasicTokenizer instead of ftfy.
[diffusers] [feature_extractor] transformers.CLIPFeatureExtractor
[oneflow] [text_encoder] transformers.OneFlowCLIPTextModel
[oneflow] [vae] diffusers.OneFlowAutoencoderKL
[oneflow] [unet] diffusers.OneFlowUNet2DConditionModel
[oneflow] [scheduler] diffusers.OneFlowPNDMScheduler
[oneflow] [safety_checker] stable_diffusion.OneFlowStableDiffusionSafetyChecker
[oneflow] compiling unet beforehand to make sure the progress bar is more accurate
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
.........
AttributeError: module 'oneflow._C' has no attribute 'fused_geglu'
############

**Comment by jackalcooper** [comment]
@xiaohaipeng are you using master branch of oneflow? You might need to uninstall it and reinstall with
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112
```

**Comment by xiaohaipeng** [comment]
yeah,you are right!your advice worked
