### ISSUE TITLE
固定种子但是两次生成结果不同的问题

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#190]
想请问为什么这样固定了种子，两次生成的图还是不一样呢，谢谢（我和webui设定了相同的提示词和种子，但是无法得到对齐的结果）
```python
from onediff import OneFlowStableDiffusionPipeline
import oneflow
import os
import time 
import oneflow as flow
flow.mock_torch.enable()
start = time.time()
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)

pipe = pipe.to("cuda")

cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)

prompt = "cat,dog,sea"
negative_prompt = "sky"

with flow.autocast("cuda"):
    images = pipe(prompt,height=512,width=512,num_images_per_prompt=1,num_inference_steps=20,).images
    end = time.time()
    print("cost time: ",end-start)


print("开始推理")
with flow.autocast("cuda"):
    print("2")
    images = pipe(prompt,negative_prompt=negative_prompt,\
                  generator=cur_generator, height=512,width=512,num_images_per_prompt=1,num_inference_steps=20).images
    
    for i, image in enumerate(images):
        image.save(f"{i}-{time.time()}.png")

    
with flow.autocast("cuda"):
    print("2")
    start = time.time()
    images = pipe(prompt,negative_prompt=negative_prompt,height=512,width=512,\
                  generator=cur_generator,num_images_per_prompt=1,num_inference_steps=20).images
    end = time.time()
    for i, image in enumerate(images):
        image.save(f"{i}-{time.time()}.png")
    print("cost time: ",end-start)

```

**Comment by Hank0626** [comment]
加入如下一行，具体原因是generator在pipe内部会被改变，所以需要重新定义下。
```python
from onediff import OneFlowStableDiffusionPipeline
import oneflow
import os
import time 
import oneflow as flow
flow.mock_torch.enable()
start = time.time()
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    use_auth_token=True,
    revision="fp16",
    torch_dtype=flow.float16,
)

pipe = pipe.to("cuda")

cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)

prompt = "cat,dog,sea"
negative_prompt = "sky"

with flow.autocast("cuda"):
    images = pipe(prompt,height=512,width=512,num_images_per_prompt=1,num_inference_steps=20,).images
    end = time.time()
    print("cost time: ",end-start)

cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)  # 加这一行就行了

print("开始推理")
with flow.autocast("cuda"):
    print("2")
    images = pipe(prompt,negative_prompt=negative_prompt,\
                  generator=cur_generator, height=512,width=512,num_images_per_prompt=1,num_inference_steps=20).images
    
    for i, image in enumerate(images):
        image.save(f"{i}-{time.time()}.png")

    
with flow.autocast("cuda"):
    print("2")
    start = time.time()
    images = pipe(prompt,negative_prompt=negative_prompt,height=512,width=512,\
                  generator=cur_generator,num_images_per_prompt=1,num_inference_steps=20).images
    end = time.time()
    for i, image in enumerate(images):
        image.save(f"{i}-{time.time()}.png")
    print("cost time: ",end-start)
```

**Comment by sanbuphy** [comment]
> 加入如下一行，具体原因是generator在pipe内部会被改变，所以需要重新定义下。我在本地生成出来，应该还是会有一些微小的区别，这是由于开启graph模式有一点点误差，不过一般来说，图像分辨率在768-1024，误差会减小，因为"runwayml/stable-diffusion-v1-5"是在512上训练，继续又在768分辨率上训练的。
> 
> ```python
> from onediff import OneFlowStableDiffusionPipeline
> import oneflow
> import os
> import time 
> import oneflow as flow
> flow.mock_torch.enable()
> start = time.time()
> pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>     "runwayml/stable-diffusion-v1-5",
>     use_auth_token=True,
>     revision="fp16",
>     torch_dtype=flow.float16,
> )
> 
> pipe = pipe.to("cuda")
> 
> cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)
> 
> prompt = "cat,dog,sea"
> negative_prompt = "sky"
> 
> with flow.autocast("cuda"):
>     images = pipe(prompt,height=512,width=512,num_images_per_prompt=1,num_inference_steps=20,).images
>     end = time.time()
>     print("cost time: ",end-start)
> 
> cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)  # 加这行
> 
> print("开始推理")
> with flow.autocast("cuda"):
>     print("2")
>     images = pipe(prompt,negative_prompt=negative_prompt,\
>                   generator=cur_generator, height=512,width=512,num_images_per_prompt=1,num_inference_steps=20).images
>     
>     for i, image in enumerate(images):
>         image.save(f"{i}-{time.time()}.png")
> 
> cur_generator = oneflow.Generator("cuda").manual_seed(1528134293)  # 加这行
>     
> with flow.autocast("cuda"):
>     print("2")
>     start = time.time()
>     images = pipe(prompt,negative_prompt=negative_prompt,height=512,width=512,\
>                   generator=cur_generator,num_images_per_prompt=1,num_inference_steps=20).images
>     end = time.time()
>     for i, image in enumerate(images):
>         image.save(f"{i}-{time.time()}.png")
>     print("cost time: ",end-start)
> ```


谢谢，看来是直接传引用没有经过拷贝，我发现确实微小的举动可以造成巨大的变化，我还想请教几个问题：
1、webui和onedif不能对齐的最大原因是不是因为webui维护了自己的一套prompt的encoder？
2、对于采样，onedif默认的schedule方法是什么呢？
非常感谢。

**Comment by Hank0626** [comment]
1. 这个问题放到这个issue里面吧https://github.com/Oneflow-Inc/diffusers/issues/194
2. text2img应该是DDIM Scheduler

**Comment by sanbuphy** [comment]
> 1. 这个问题放到这个issue里面吧[参数与webui对齐但是不能得到相同结果的问题 #194](https://github.com/Oneflow-Inc/diffusers/issues/194)
> 2. text2img应该是DDIM Scheduler

好的，在这个新issue中调查
