### ISSUE TITLE
Oneflow Diffusers Breaking after Oneflow Update

### ISSUE THREAD

**Issue by abi98213** [Oneflow-Inc/diffusers#198]
Onediff  has started to break after the recent release of newer nighly version of oneflow. I am using onediff.demo and after changing one aspect ratio it is breaking on another aspect ratio.
Please see what is happening

```
Traceback (most recent call last):
  File "test_service.py", line 23, in <module>
    img = pipe("A beautiful girl", width = item, height = item)
  File "/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "onediff/pipeline_stable_diffusion_oneflow.py", line 703, in __call__
    noise_pred = unet_graph(latent_model_input, t, text_embeddings)
  File "oneflow/nn/graph/graph.py", line 268, in __call__
    return self._dynamic_input_graph_cache(*args, **kwargs)
  File "oneflow/nn/graph/cache.py", line 115, in __call__
    return graph(*args, **kwargs)
  File oneflow/nn/graph/graph.py", line 271, in __call__
    self._compile(*args, **kwargs)
  File "oneflow/nn/graph/graph.py", line 841, in _compile
    return self._compile_from_shared(*args, **kwargs)
  File "oneflow/nn/graph/graph.py", line 958, in _compile_from_shared
    self._c_nn_graph.build_with_new_input_from_shared_graph(
oneflow._oneflow_internal.exception.RuntimeError: Error: Check failed: (21 == 22) 
```

**Comment by jackalcooper** [comment]
we will look into it. the nightly release's intended purpose is to catch the bug ASAP.

**Comment by jackalcooper** [comment]
I managed to run the demo command without error. My oneflow doctor output
```
python3 -m oneflow --doctor
path: ['/home/caishenghang/.local/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230419+cu117
git_commit: 99b71264
cmake_build_type: Release
rdma: True
mlir: True
```
Could you post yours?

**Comment by abi98213** [comment]
This is the output 
    `path: ['/home/ubuntu/bento/stable-diffusion-bentoml/env2/lib/python3.10/site-packages/oneflow']
    version: 0.9.1.dev20230415+cu117
    git_commit: 2cad022
    cmake_build_type: Release
    rdma: True
    mlir: True
`

This is the code
    
    `import oneflow as flow
    
    flow.mock_torch.enable()
    from onediff import OneFlowStableDiffusionPipeline
    from diffusers.schedulers import (
        DPMSolverMultistepScheduler,
    )
    model_id = "runwayml/stable-diffusion-v1-5"
    schedulers = {
        "DPM++": DPMSolverMultistepScheduler.from_pretrained(model_id, subfolder="scheduler"),
    }
    
    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
        model_id,
        use_auth_token=True,
        torch_dtype=flow.float16,
    )
    
    import time 
    from collections import defaultdict
    
    pipe = pipe.to("cuda")
    pipe.set_graph_compile_cache_size(9)
    import random
    
    size = [[512,512], [512,768], [768,512]]
    
    size = [[648,368], [512,512]]
    
    for i in range(100):
        item = random.choice(size)
        h = item[0]
        w = item[1]
    
        print(f'Height and width is {h} {w}')
    
        images = pipe(
            prompt="""
            A horse
            """,
            negative_prompt="""
            ugly
            """
            ,
            height=h,
            width=w,
            num_inference_steps=60,
            guidance_scale=7,
            output_type="np",
        ).images
    `
And it is breaking on second height and width always
@jackalcooper @doombeaker

**Comment by abi98213** [comment]
Solved it. The issue was inconsistent sizes
