### ISSUE TITLE
TypeError: Cannot interpret 'oneflow.float64' as a data type

### ISSUE THREAD

**Issue by HuaZheLei** [Oneflow-Inc/diffusers#20]
### Describe the bug

When run fp16 version descrided in https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion, I find this error.
However, the fp32 version works well.

### Reproduction

```python
import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline
import timeit

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "./stable-diffusion-v1-4",
    revision="fp16",
    torch_dtype=torch.float16,
)

pipe = pipe.to("cuda")

start = timeit.default_timer()
prompt = "a photo of an astronaut riding a horse on mars"
with torch.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-of-{i}.png")

end = timeit.default_timer()
print('Running time: %s Seconds' % (end - start))
```
### Logs

```shell
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
[oneflow] [vae] diffusers.OneFlowAutoencoderKL
[diffusers] [tokenizer] transformers.CLIPTokenizer
[oneflow] [unet] diffusers.OneFlowUNet2DConditionModel
[oneflow] [safety_checker] stable_diffusion.OneFlowStableDiffusionSafetyChecker
[oneflow] [scheduler] diffusers.OneFlowPNDMScheduler
[diffusers] [feature_extractor] transformers.CLIPFeatureExtractor
[oneflow] [text_encoder] transformers.OneFlowCLIPTextModel
[oneflow] compiling unet beforehand to make sure the progress bar is more accurate
[oneflow] [elapsed(s)] [unet compilation] 25.13586367602693
 98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 50/51 [00:02<00:00, 22.99it/s]
Traceback (most recent call last):
  File "demo.py", line 17, in <module>
    images = pipe(prompt).images
  File "/opt/conda/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/code/diffusion/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 321, in __call__
    latents = self.scheduler.step(noise_pred, t, latents, **extra_step_kwargs).prev_sample
  File "/code/diffusion/diffusers/src/diffusers/schedulers/scheduling_pndm_oneflow.py", line 223, in step
    return self.step_plms(model_output=model_output, timestep=timestep, sample=sample, return_dict=return_dict)
  File "/code/diffusion/diffusers/src/diffusers/schedulers/scheduling_pndm_oneflow.py", line 338, in step_plms
    prev_sample = self._get_prev_sample(sample, timestep, prev_timestep, model_output)
  File "/code/diffusion/diffusers/src/diffusers/schedulers/scheduling_pndm_oneflow.py", line 362, in _get_prev_sample
    if (alpha_prod_t_prev.dtype == torch.float64):
TypeError: Cannot interpret 'oneflow.float64' as a data type
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-4.18.0-2.4.3.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.8
- PyTorch version (GPU?): 1.10.0+cu111 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.0.dev0
- Using GPU in script?: True
- Using distributed or parallel set-up in script?: <fill in>

**Comment by jackalcooper** [comment]
Hi @HuaZheLei , happy to receive feedback from you.
I tried to run the code you posted and it works. Did you install oneflow with this command?
```
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112
```

**Comment by HuaZheLei** [comment]
> 

Thanks for your reply!

**Comment by HuaZheLei** [comment]
> Hi @HuaZheLei , happy to receive feedback from you. I tried to run the code you posted and it works. Did you install oneflow with this command?
> 
> ```
> python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112
> ```


Thanks for your reply!
I do install oneflow with the command `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112`.
But because my cuda version is 11.4, I firstly install with cu114. Then I find some errors, I uninstall oneflow, and reinstall with cu112. Now, I think maybe I do not clean the old version totally.

**Comment by jackalcooper** [comment]
> But because my cuda version is 11.4, I firstly install with cu114

It is ok to run a cu112 oneflow with CUDA toolkit 11.4 because oneflow has bundled the CUDA runtime.

> Could you run `python3 -m oneflow --doctor`? This is what it prints in my terminal:
```
loaded library: /lib/x86_64-linux-gnu/libibverbs.so.1
path: ['......']
version: 0.8.1+cu112.git.5610333
git_commit: 5610333
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by jackalcooper** [comment]
@HuaZheLei after some digging around, I found that this could be related to the version of numpy. The version in my env is 1.23.4

**Comment by HuaZheLei** [comment]
> @HuaZheLei after some digging around, I found that this could be related to the version of numpy. The version in my env is 1.23.4

Cool! It works. But the result is a little bit weird.

**Comment by jackalcooper** [comment]
> Cool! It works. But the result is a little bit weird.

You might consider to pull the branch `oneflow-fork` and update it to the latest to get a better result.
