### ISSUE TITLE
safe格式权重的读取支持

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#200]
请问onediffuser是否有对webui的safetensors的官方接口支持？
或者可以类似huggingdiffuser的转换器支持？
我想参考：https://www.sohu.com/a/653640047_129720
做一些尝试，谢谢。

**Comment by jackalcooper** [comment]
是可行的，已经跑通了基本的接口，之后完善了会放出～

**Comment by sanbuphy** [comment]
> 是可行的，已经跑通了基本的接口，之后完善了会放出～

感谢，作为替代方案，我能否先用diffusers的官方导出？，然后使用默认的方法进行读取

**Comment by jackalcooper** [comment]
> > 是可行的，已经跑通了基本的接口，之后完善了会放出～
> 
> 感谢，作为替代方案，我能否先用diffusers的官方导出？，然后使用默认的方法进行读取

应该是可以的

**Comment by sanbuphy** [comment]
> > > 是可行的，已经跑通了基本的接口，之后完善了会放出～
> > 
> > 
> > 感谢，作为替代方案，我能否先用diffusers的官方导出？，然后使用默认的方法进行读取
> 
> 应该是可以的

已经成功。请问lora也可以用类似的方法去实现吗？

**Comment by daquexian** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/10171 oneflow 已经可以加载 safetensors 格式，明天的 nightly 就可以用了

**Comment by sanbuphy** [comment]
> [Oneflow-Inc/oneflow#10171](https://github.com/Oneflow-Inc/oneflow/pull/10171) oneflow 已经可以加载 safetensors 格式，明天的 nightly 就会包含这个改动了

谢谢大老师，研发大哥牛逼
