### ISSUE TITLE
Community pipeline usage, long prompt weighting

### ISSUE THREAD

**Issue by NicholasKao1029** [Oneflow-Inc/diffusers#202]
I want to use this community pipeline with oneflow [lpw](https://github.com/huggingface/diffusers/blob/7e6886f5e93ca9bb1e6d4beece46fe1e43b819c2/examples/community/lpw_stable_diffusion.py#L403), it inherits from the diffusers pipeline, and is known as a [community pipeline](https://huggingface.co/docs/diffusers/using-diffusers/contribute_pipeline). 

Is there a way to use this with onediff?

tried using [custom_pipeline](https://huggingface.co/docs/diffusers/using-diffusers/custom_pipeline_examples#long-prompt-weighting-stable-diffusion) but doesn't work because onediff specific methods such as `set_graph_compile_cache_size` don't exist.

**Comment by Hank0626** [comment]
We haven't migrated the lpw yet from diffusers to onediff.
