### ISSUE TITLE
关于oneflow在腾讯云V100机器上提升不明显的问题

### ISSUE THREAD

**Issue by hihei** [Oneflow-Inc/diffusers#204]
关于oneflow在腾讯云V100机器上提升不明显的问题
硬件环境: 10c40G, 显卡V100，显存32G
<img width="560" alt="image" src="https://user-images.githubusercontent.com/17537331/233826687-6142f515-ad0d-4db4-b1b2-434a99fe13a3.png">

生成耗时:
基于sd1.4的模型，推理360 * 720的图片5张:
diffusers耗时:  8.07s, oneflow耗时: 6.34s

软件环境(oneflow):
```
-> % python -m oneflow --doctor                                                                      path: ['/data/gpu_env_common/env/anaconda3/envs/sd_oneflow_test/lib/python3.9/site-packages/oneflow']
version: 0.9.1.dev20230422+cu117
git_commit: 53ed8044
cmake_build_type: Release
rdma: True
mlir: True
----------------
安装命令:
yum install libibverbs libibverbs-devel libibverbs-utils -y
oneflow 环境搭建:
conda create -n sd_oneflow_test  python=3.9
python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117
python3 -m pip install "torch<2" "transformers>=4.26" "diffusers[torch]==0.14.0"
python3 -m pip uninstall accelerate -y
python3 -m pip install onediff
python3 -m onediff.demo
```
测试代码:
```
def process_v1():
    import time
    import numpy as np
    import os
    import imageio

    import oneflow as flow
    flow.mock_torch.enable()
    from oneflow import autocast

    from diffusers import DDIMScheduler
    from onediff import OneFlowStableDiffusionPipeline as StableDiffusionPipeline

    st = time.time()
    image_output_folder = 'dreamlike-anime-oneflow'
    model_path = "CompVis/stable-diffusion-v1-4"

    scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False,
                              set_alpha_to_one=False)
    pipe = StableDiffusionPipeline.from_pretrained(model_path, scheduler=scheduler, safety_checker=None,
                                                   torch_dtype=flow.float16).to("cuda")
    print("init tm={}".format(time.time() - st))
    tms = []
    for i in range(0, 2):
        st = time.time()
        # @markdown Can set random seed here for reproducibility.
        g_cuda = flow.Generator(device='cuda')
        seed = 247839276  # @param {type:"number"}
        g_cuda.manual_seed(seed)

        # prompt = 'a cute bunny holding a microphone and singing for easter sunday, wide eyes, open mouth, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of Polaroid art, futurism, illustration, moody lighting'
        # negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"  # @param {type:"string"}

        prompt = 'a stage and a microphone, indoor, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of disney movie, futurism, illustration, moody light, dark color theme'
        negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"  # @param {type:"string"}
        num_samples = 5  # @param {type:"number"}
        guidance_scale = 7.5  # @param {type:"number"u}
        num_inference_steps = 30  # @param {type:"number"}
        height = 360  # @param {type:"number"}
        width = 720  # @param {type:"number"}

        with autocast("cuda"), flow.inference_mode():
            images = pipe(
                prompt,
                height=height,
                width=width,
                negative_prompt=negative_prompt,
                num_images_per_prompt=num_samples,
                num_inference_steps=num_inference_steps,
                guidance_scale=guidance_scale,
                generator=g_cuda
            ).images

        count = 0
        if not os.path.exists("{}".format(image_output_folder)):
            os.makedirs("{}".format(image_output_folder))
        for img in images:
            imageio.imwrite("{}/{}.png".format(image_output_folder, str(count)), img)
            count += 1
        print("time consumed: {}s".format(time.time() - st))
        tms.append(time.time() - st)
    tms = np.array(tms)
    print("mean={}, mean1={}".format(np.mean(tms), np.mean(tms[1:])))
process_v1()
```

软件环境(diffusers)
```
Package                  Version
------------------------ -----------
accelerate               0.18.0
aiofiles                 23.1.0
aiohttp                  3.8.4
aiosignal                1.3.1
altair                   4.2.2
anyio                    3.6.2
async-timeout            4.0.2
attrs                    23.1.0
bitsandbytes             0.35.0
certifi                  2022.12.7
charset-normalizer       3.1.0
click                    8.1.3
cmake                    3.26.3
contourpy                1.0.7
cycler                   0.11.0
diffusers                0.15.1
entrypoints              0.4
fastapi                  0.95.1
ffmpy                    0.3.0
filelock                 3.12.0
fonttools                4.39.3
frozenlist               1.3.3
fsspec                   2023.4.0
ftfy                     6.1.1
gradio                   3.27.0
gradio_client            0.1.3
h11                      0.14.0
httpcore                 0.17.0
httpx                    0.24.0
huggingface-hub          0.13.4
idna                     3.4
imageio                  2.27.0
importlib-metadata       6.5.0
importlib-resources      5.12.0
Jinja2                   3.1.2
jsonschema               4.17.3
kiwisolver               1.4.4
linkify-it-py            2.0.0
lit                      16.0.1
markdown-it-py           2.2.0
MarkupSafe               2.1.2
matplotlib               3.7.1
mdit-py-plugins          0.3.3
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.0.4
natsort                  8.3.1
networkx                 3.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oneflow                  0.9.0+cu118
orjson                   3.8.10
packaging                23.1
pandas                   2.0.0
Pillow                   9.5.0
pip                      23.1
protobuf                 3.20.3
psutil                   5.9.5
pydantic                 1.10.7
pydub                    0.25.1
Pygments                 2.15.1
pyparsing                3.0.9
pyrsistent               0.19.3
python-dateutil          2.8.2
python-multipart         0.0.6
pytz                     2023.3
PyYAML                   6.0
regex                    2023.3.23
requests                 2.28.2
rich                     13.3.4
semantic-version         2.10.0
setuptools               67.6.1
six                      1.16.0
sniffio                  1.3.0
starlette                0.26.1
sympy                    1.12rc1
tokenizers               0.13.3
toolz                    0.12.0
torch                    2.0.0
tqdm                     4.65.0
transformers             4.28.1
triton                   2.0.0
typing_extensions        4.5.0
tzdata                   2023.3
uc-micro-py              1.0.1
urllib3                  1.26.15
uvicorn                  0.21.1
wcwidth                  0.2.6
websockets               11.0.2
wheel                    0.40.0
yarl                     1.8.2
zipp                     3.15.0
---------
安装方式:
pip install diffusers -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install -q -U --pre triton -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install -q accelerate transformers ftfy bitsandbytes==0.35.0 gradio natsort -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install torch -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install opencv-python
pip install imageio
```

测试代码
```
def process_v1():
    import time
    import numpy as np
    import os
    import imageio

    from torch import autocast
    import torch
    from diffusers import DDIMScheduler
    from diffusers import StableDiffusionPipeline

    st = time.time()
    image_output_folder = 'dreamlike-anime-oneflow'
    model_path = "CompVis/stable-diffusion-v1-4"

    scheduler = DDIMScheduler(beta_start=0.00085, beta_end=0.012, beta_schedule="scaled_linear", clip_sample=False,
                              set_alpha_to_one=False)
    pipe = StableDiffusionPipeline.from_pretrained(model_path, scheduler=scheduler, safety_checker=None,
                                                   torch_dtype=torch.float16).to("cuda")
    print("init tm={}".format(time.time() - st))
    tms = []
    for i in range(0, 2):
        st = time.time()
        # @markdown Can set random seed here for reproducibility.
        g_cuda = torch.Generator(device='cuda')
        seed = 247839276  # @param {type:"number"}
        g_cuda.manual_seed(seed)

        # prompt = 'a cute bunny holding a microphone and singing for easter sunday, wide eyes, open mouth, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of Polaroid art, futurism, illustration, moody lighting'
        # negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"  # @param {type:"string"}

        prompt = 'a stage and a microphone, indoor, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of disney movie, futurism, illustration, moody light, dark color theme'
        negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"  # @param {type:"string"}
        num_samples = 5  # @param {type:"number"}
        guidance_scale = 7.5  # @param {type:"number"u}
        num_inference_steps = 30  # @param {type:"number"}
        height = 360  # @param {type:"number"}
        width = 720  # @param {type:"number"}

        with autocast("cuda"), torch.inference_mode():
            images = pipe(
                prompt,
                height=height,
                width=width,
                negative_prompt=negative_prompt,
                num_images_per_prompt=num_samples,
                num_inference_steps=num_inference_steps,
                guidance_scale=guidance_scale,
                generator=g_cuda
            ).images

        count = 0
        if not os.path.exists("{}".format(image_output_folder)):
            os.makedirs("{}".format(image_output_folder))
        for img in images:
            imageio.imwrite("{}/{}.png".format(image_output_folder, str(count)), img)
            count += 1
        print("time consumed: {}s".format(time.time() - st))
        tms.append(time.time() - st)
    tms = np.array(tms)
    print("mean={}, mean1={}".format(np.mean(tms), np.mean(tms[1:])))


process_v1()

```

**Comment by Hank0626** [comment]
可以试跑一下以下的代码：
```python
import oneflow as flow
import time
model_id = "CompVis/stable-diffusion-v1-4"
height = 360
width = 720
prompt = 'a stage and a microphone, indoor, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of disney movie, futurism, illustration, moody light, dark color theme'
negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"
test_times = 5  
num_samples = 5  
num_inference_steps = 30
def diffusers_inference():
    with flow.mock_torch.disable():
        from diffusers import StableDiffusionPipeline
        import torch

        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            use_auth_token=True,
            revision="fp16",
            torch_dtype=torch.float16,
        )

        pipe = pipe.to("cuda")

        cur_generator = torch.Generator("cuda").manual_seed(1528134293)

        print("Diffusers Begin Inference")
        with torch.autocast("cuda"):
            start = time.time()
            for i in range(test_times):
                images_diffusers = pipe(
                    prompt,
                    negative_prompt=negative_prompt,
                    generator=cur_generator,
                    height=height,
                    width=width,
                    num_images_per_prompt=num_samples,
                    num_inference_steps=num_inference_steps,
                    output_type="np",
                ).images
            print(f"Diffusers Inference Time: {(time.time() - start) / test_times:.2f}s, (mean of {test_times} times)")

def onediff_inference():
    from onediff import OneFlowStableDiffusionPipeline

    pipe = OneFlowStableDiffusionPipeline.from_pretrained(
        model_id,
        use_auth_token=True,
        revision="fp16",
        torch_dtype=flow.float16,
    )

    pipe = pipe.to("cuda")

    cur_generator = flow.Generator("cuda").manual_seed(1528134293)

    print("Onediff Begin Warmup")
    with flow.autocast("cuda"), flow.inference_mode():
        images_onediff = pipe(
            prompt,
            negative_prompt=negative_prompt,
            generator=cur_generator,
            height=height,
            width=width,
            num_images_per_prompt=num_samples,
            num_inference_steps=num_inference_steps,
            output_type="np",
        ).images
    print("Onediff Warmup Done")
    print("Onediff Begin Inference")
    with flow.autocast("cuda"):
        start = time.time()
        for i in range(test_times):
            images_onediff = pipe(
                prompt,
                negative_prompt=negative_prompt,
                generator=cur_generator,
                height=height,
                width=width,
                num_images_per_prompt=num_samples,
                num_inference_steps=num_inference_steps,
                output_type="np",
            ).images
        print(f"Onediff Inference Time: {(time.time() - start) / test_times:.2f}s, (mean of {test_times} times)")
        
if __name__=="__main__":
    onediff_inference()
    flow.framework.session_context.TryCloseDefaultSession()
    flow.framework.session_context.NewDefaultSession(flow._oneflow_global_unique_env)
    diffusers_inference()
```
在3090上，我的结果是：
```
Onediff Begin Inference
100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.99it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.00it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
Onediff Inference Time: 4.21s, (mean of 5 times)
Diffusers Begin Inference
100%|████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.50it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.50it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.51it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.51it/s]
100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.50it/s]
Diffusers Inference Time: 12.57s, (mean of 5 times)
```

**Comment by hihei** [comment]
> 可以试跑一下以下的代码，在diffusers的环境下运行`diffusers_inference`，在onediff环境下运行`onediff_inference`：
> 
> ```python
> import oneflow as flow
> import time
> 
> model_id = "CompVis/stable-diffusion-v1-4"
> height = 360
> width = 720
> prompt = "a stage and a microphone, indoor, masterpiece, best quality, absurdres, 8k resolution, highly detailed, official art, style of disney movie, futurism, illustration, moody light, dark color theme"
> negative_prompt = "nude, naked, out of frame, duplicate, watermark, signature, text, ugly, morbid, mutated, deformed, blurry, bad anatomy, bad proportions, cloned face, disfigured, fused fingers, fused limbs, too many fingers, long neck"
> test_times = 5
> num_samples = 5
> num_inference_steps = 30
> 
> 
> def diffusers_inference():
>     with flow.mock_torch.disable():
>         from diffusers import StableDiffusionPipeline
>         import torch
> 
>         pipe = StableDiffusionPipeline.from_pretrained(
>             model_id,
>             use_auth_token=True,
>             revision="fp16",
>             torch_dtype=torch.float16,
>         )
> 
>         pipe = pipe.to("cuda")
> 
>         cur_generator = torch.Generator("cuda").manual_seed(1528134293)
> 
>         print("Diffusers Begin Inference")
>         with torch.autocast("cuda"):
>             start = time.time()
>             for i in range(test_times):
>                 images_diffusers = pipe(
>                     prompt,
>                     negative_prompt=negative_prompt,
>                     generator=cur_generator,
>                     height=height,
>                     width=width,
>                     num_images_per_prompt=num_samples,
>                     num_inference_steps=num_inference_steps,
>                     output_type="np",
>                 ).images
>             print(
>                 f"Diffusers Inference Time: {(time.time() - start) / test_times:.2f}s, (mean of {test_times} times)"
>             )
> 
> 
> def onediff_inference():
>     from onediff import OneFlowStableDiffusionPipeline
> 
>     pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>         model_id,
>         use_auth_token=True,
>         revision="fp16",
>         torch_dtype=flow.float16,
>     )
> 
>     pipe = pipe.to("cuda")
> 
>     cur_generator = flow.Generator("cuda").manual_seed(1528134293)
> 
>     print("Onediff Begin Warmup")
>     with flow.autocast("cuda"), flow.inference_mode():
>         images_onediff = pipe(
>             prompt,
>             negative_prompt=negative_prompt,
>             generator=cur_generator,
>             height=height,
>             width=width,
>             num_images_per_prompt=num_samples,
>             num_inference_steps=num_inference_steps,
>             output_type="np",
>         ).images
>     print("Onediff Warmup Done")
>     print("Onediff Begin Inference")
>     with flow.autocast("cuda"):
>         start = time.time()
>         for i in range(test_times):
>             images_onediff = pipe(
>                 prompt,
>                 negative_prompt=negative_prompt,
>                 generator=cur_generator,
>                 height=height,
>                 width=width,
>                 num_images_per_prompt=num_samples,
>                 num_inference_steps=num_inference_steps,
>                 output_type="np",
>             ).images
>         print(
>             f"Onediff Inference Time: {(time.time() - start) / test_times:.2f}s, (mean of {test_times} times)"
>         )
> 
> 
> if __name__ == "__main__":
>     onediff_inference()
>     flow.framework.session_context.TryCloseDefaultSession()
>     flow.framework.session_context.NewDefaultSession(flow._oneflow_global_unique_env)
>     diffusers_inference()
> ```
> 
> 在3090上，我的结果是：
> 
> ```
> Onediff Begin Inference
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.99it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  8.00it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:03<00:00,  7.98it/s]
> Onediff Inference Time: 4.21s, (mean of 5 times)
> Diffusers Begin Inference
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.50it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.50it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.51it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.51it/s]
> 100%|████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.50it/s]
> Diffusers Inference Time: 12.57s, (mean of 5 times)
> ```

libibverbs not available, ibv_fork_init skipped
The cache for model files in Diffusers v0.14.0 has moved to a new location. Moving your existing cached models. This is a one-time operation, you can interrupt it or run it later by calling `diffusers.utils.hub_utils.move_cache()`.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
/data/gpu_env_common/env/anaconda3/envs/sd_oneflow_test/lib/python3.9/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Onediff Begin Warmup
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.71it/s]
Onediff Warmup Done
Onediff Begin Inference
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.70it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.69it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.69it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.69it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:05<00:00,  5.68it/s]
Onediff Inference Time: 5.88s, (mean of 5 times)
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
Cannot initialize model with low cpu memory usage because `accelerate` was not found in the environment. Defaulting to `low_cpu_mem_usage=False`. It is strongly recommended to install `accelerate` for faster and less memory-intense model loading. You can do so with:
```
pip install accelerate
```
.
/data/gpu_env_common/env/anaconda3/envs/sd_oneflow_test/lib/python3.9/site-packages/transformers/models/clip/feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Diffusers Begin Inference
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.38it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.39it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.39it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.39it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:12<00:00,  2.39it/s]
Diffusers Inference Time: 13.17s, (mean of 5 times)

**Comment by hihei** [comment]
测试后发现是torch2.0版本的速度有明显提升，所以致使oneflow和pytorch相比提升不是很明显。
相同代码:
torch1.9版本： Diffusers Inference Time: 14.30s, (mean of 5 times)

**Comment by CrazyBoyM** [comment]
> 测试后发现是torch2.0版本的速度有明显提升，所以致使oneflow和pytorch相比提升不是很明显。 相同代码: torch1.9版本： Diffusers Inference Time: 14.30s, (mean of 5 times) torch2.0版本: Diffusers Inference Time: 8.27s, (mean of 5 times)

提速差距很小是否说明没必要再切换兼容到oneflow的加速方案了？想咨询一下现在有更好的加速方案嘛，比如torch2的torch.compile(model)或者nvidia的tensorRT方案？

**Comment by HoiM** [comment]
我也遇到类似问题，V100上compile以后速度下降。我使用的是Stable Video Diffusion模型。

**Comment by strint** [comment]
Please see this about Device Compatibility: https://github.com/siliconflow/onediff/wiki/Compatibility-with-Nvidia-GPUs
