### ISSUE TITLE
[bug]RuntimeError: [1m[38;2;255;000;000mError[0m: kFloat16 .vs kFloat

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#211]
I want to run this model （kubanemil/chilloutmix_NiPrunedFp32Fix）with the float16 data type, but I meet an error.
![image](https://github.com/Oneflow-Inc/diffusers/assets/96160062/bffa5945-6647-4d67-ad66-fd60772de7dc)

I can run float16 perfectly on HuggingFace diffuser.
here is my code : 

```python
from onediff import OneFlowStableDiffusionPipeline
import oneflow
import os
import time 
from diffusers import DDIMScheduler,DPMSolverMultistepScheduler,\
    EulerAncestralDiscreteScheduler,EulerDiscreteScheduler

import oneflow as flow
flow.mock_torch.enable()

model_id = "kubanemil/chilloutmix_NiPrunedFp32Fix"
scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    model_id,
    use_auth_token=True,
    # revision="fp16",
    torch_dtype=flow.float16,
    scheduler = scheduler
)
pipe.to("cuda")

prompt = "realistic, beautiful female,long hair, long sleeves, shirt,jeans,sitting,outdoors,ivy,table,cityscape,glass,from above , looking at viewer, office,parted lips:, light_smile, shiny skin, skindentation"
neprompt = "sketches,worst quality, lowres, normal quality, nail polish,(holding,cup,smoke),wall,police hat, film grain,curvy,nsfw,covered nipples, mole, skin spots, acnes, skin blemishes, age spot,young, child, loli"

with flow.autocast("cuda"):
    images = pipe(prompt,negative_prompt=neprompt, height=512,width=512,num_images_per_prompt=1,\
                  num_inference_steps=20).images
    for i, image in enumerate(images):
        image.save(f"{i}-{time.time()}-{prompt}-{seed}.png")

```

**Comment by sanbuphy** [comment]
目前猜测和某个库的版本有关系。我使用二、三周前部署的onedif测试是没有问题的

**Comment by sanbuphy** [comment]
> My oneflow version is:
> 
> ```
> version: 0.9.1.dev20230507+cu117
> git_commit: 0d4bc37
> cmake_build_type: Release
> rdma: True
> mlir: True
> ```
> 
> diffusers `0.15.0` transformers `4.27.1` onediff is the latest version. And I am ok with this code snippet:
> 
> ```python
> from onediff import OneFlowStableDiffusionPipeline
> import oneflow
> import os
> import time 
> from diffusers import DDIMScheduler,DPMSolverMultistepScheduler,\
>     EulerAncestralDiscreteScheduler,EulerDiscreteScheduler
> 
> import oneflow as flow
> flow.mock_torch.enable()
> 
> model_id = "kubanemil/chilloutmix_NiPrunedFp32Fix"
> scheduler = EulerDiscreteScheduler.from_pretrained(model_id, subfolder="scheduler")
> pipe = OneFlowStableDiffusionPipeline.from_pretrained(
>     model_id,
>     use_auth_token=True,
>     # revision="fp16",
>     torch_dtype=flow.float16,
>     scheduler = scheduler
> )
> pipe.to("cuda")
> 
> prompt = "realistic, beautiful female,long hair, long sleeves, shirt,jeans,sitting,outdoors,ivy,table,cityscape,glass,from above , looking at viewer, office,parted lips:, light_smile, shiny skin, skindentation"
> neprompt = "sketches,worst quality, lowres, normal quality, nail polish,(holding,cup,smoke),wall,police hat, film grain,curvy,nsfw,covered nipples, mole, skin spots, acnes, skin blemishes, age spot,young, child, loli"
> 
> with flow.autocast("cuda"):
>     images = pipe(prompt,negative_prompt=neprompt, height=512,width=512,num_images_per_prompt=1,\
>                   num_inference_steps=20).images
>     for i, image in enumerate(images):
>         image.save(f"{i}-{time.time()}-{prompt}.png")  # without seed
> ```

Hi, Here is my version:
python3.8     diffusers  0.15.0
![image](https://github.com/Oneflow-Inc/diffusers/assets/96160062/43c6a2ec-f864-4d37-aa6a-1da973241fbc)

**Comment by Hank0626** [comment]
It is the problem of the version of `transformers`, I think you can downgrade it to `4.27.1`

**Comment by sanbuphy** [comment]
> It is the problem of the version of `transformers`, I think you can downgrade it to `4.27.1`

yes, I tested transformers 4.27.1 , it work well.
