### ISSUE TITLE
请问为什么现在的动态推理还是比静态图推理的速度慢很多？

### ISSUE THREAD

**Issue by sanbuphy** [Oneflow-Inc/diffusers#212]
当前的速度比较：
正常的推理pipeline 大概是 10it/s ，而在静态图的情况下可以到17it/s

我想请问一下速度差距为什么会这么大呢（我清晰记得在几个版本前动态推理也是大概在14it/s的，似乎在更新后就永久的变慢了）
测试机器为3060

**Comment by sanbuphy** [comment]
最新* 
我降级了transforms库的等级，似乎就正常了，动态图也可以跑16it/s。
理论上是不是动态和转静态读取的速度不会差太多呢？

**Comment by strint** [comment]
可以试下最新版本：https://github.com/Oneflow-Inc/diffusers/releases/tag/0.11.0

**Comment by sanbuphy** [comment]
> 可以试下最新版本：https://github.com/Oneflow-Inc/diffusers/releases/tag/0.11.0

好的，非常开心看到oneflow又活过来了！ 祝你们一切顺利。
顺带推荐一个我觉得很不错的工作 https://github.com/chengzeyi/stable-fast/
