### ISSUE TITLE
support for inpaint and inpaint_legacy

### ISSUE THREAD

**Issue by CrazyBoyM** [Oneflow-Inc/diffusers#23]
request to add oneflow pipe as the diffusers repo code file: 
[pipeline_stable_diffusion_inpaint.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint.py)

[pipeline_stable_diffusion_inpaint_legacy.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_inpaint_legacy.py)

**Comment by jackalcooper** [comment]
🫡 working on it

**Comment by tripathiarpan20** [comment]
Hi @jackalcooper .
Thanks for the amazing open-source repository!
Is the Inpaint pipeline integrated?

Thanks.

**Comment by jackalcooper** [comment]
@tripathiarpan20 would you be interested in implementing this and make a PR?

**Comment by tripathiarpan20** [comment]
Sadly I am preoccupied with several other tasks, would have loved to!.
