### ISSUE TITLE
推理时候动态batch和动态size

### ISSUE THREAD

**Issue by Xiangyu-CAS** [Oneflow-Inc/diffusers#230]
您好，我用oneflow + diffusers在A100上优化推理了，速度非常快，感谢你们的工作

但是优化完以后是只能固定的batch和宽高吗? 我用以下代码跑会在第二条的时候崩溃

```
with flow.autocast("cuda"):
    for i in range(5):
        images = pipe(prompt, height=768, width=512, num_inference_steps=20, num_images_per_prompt=1,
                      compile_unet=True, compile_vae=True).images
        images = pipe(prompt, height=512, width=512, num_inference_steps=20, num_images_per_prompt=1,
                      compile_unet=True, compile_vae=True).images
```

**Comment by strint** [comment]
报错信息是什么的呢？

看起来是类似这个 issue：https://github.com/Oneflow-Inc/oneflow/issues/10156

已经在  https://github.com/Oneflow-Inc/oneflow/pull/10279 修复。

你看下是否是 oneflow 的最新 nightly release 。https://github.com/Oneflow-Inc/oneflow#install-with-pip-package

**Comment by strint** [comment]
> 固定的batch和宽高吗

对了，宽高是支持动态的，但是 batch 需要是固定的（一些优化技巧带来的约束）。

**Comment by Amber0130** [comment]
oneflow版本
<img width="584" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/36c2e0df-6a3e-4d86-9dbd-d7cd02979e8b">
更换图片大小还会报错
<img width="1243" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/9143d4e7-a544-46b5-9524-bc953baebf27">

**Comment by strint** [comment]
你试下这个测试样例看是否能通过：https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py

这里面有多图推理的逻辑。

**Comment by Amber0130** [comment]
> 



> 你试下这个测试样例看是否能通过：https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py
> 
> 这里面有多shape推理的逻辑。
你好，多个shape还是有这样的问题
<img width="1060" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/8d072a87-f95a-414c-b4f8-1acd84836e7b">

**Comment by strint** [comment]
> > 
> 
> > 你试下这个测试样例看是否能通过：https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py
> > 这里面有多shape推理的逻辑。
> > 你好，多个shape还是有这样的问题
> 
> <img alt="image" width="1060" src="https://user-images.githubusercontent.com/54001386/256795636-8d072a87-f95a-414c-b4f8-1acd84836e7b.png">


这个提示信息不影响正确性，请暂时忽略，我们这两天会 fix 这个 warning。
