### ISSUE TITLE
Is This No Longer Being Actively Developed?

### ISSUE THREAD

**Issue by PaulFidika** [Oneflow-Inc/diffusers#233]
Has Oneflow-inc decided to no longer continue development of thius diffusers implementation? What's the future of this project look like? Is this being replaced with another library, being developed internally or by someone else?

Currently OneFlow supports diffusers v0.15, but the rest of the world's already move on to diffusers v0.20, making it increasingly outdated. Thanks.

**Comment by jackalcooper** [comment]
hi @PaulFidika 
The development is going to continue. We are developing something new and the most significant feature could be PyTorch 2.0 `torch.compile` oneflow backend. 
There should be a new version out this week or next week.
In the meantime, we are also eager to hear more from your use cases and what features are desired beyond diffusers v0.20 support. Free free to post it here on GitHub or send me an email caishenghang@oneflow.org 😊

**Comment by diagonalge** [comment]
@jackalcooper thats good to know! We are using it in our production servers but now we are getting bottlenecks because the diffusers version that oneflow uses is too old, there are a lot of new features on the latest diffusers

**Comment by diagonalge** [comment]
@jackalcooper can we expect oneflow SD pipelines to be independent from the diffusers version?

**Comment by PaulFidika** [comment]
Great! Thanks for the fast response; I'm looking forward to seeing the next iteration!
