### ISSUE TITLE
support for negative_prompt

### ISSUE THREAD

**Issue by CrazyBoyM** [Oneflow-Inc/diffusers#24]
the negative prompt is very useful to improve the quality of image in txt2img, img2img and inpaint tasks.Is it possible for oneflow to support it?

[pipeline_stable_diffusion.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py)

**Comment by jackalcooper** [comment]
Very insightful suggestion. Soon I will upgrade the code the HEAD of upstream.
