### ISSUE TITLE
how can I use cache model?

### ISSUE THREAD

**Issue by zyx1213271098** [Oneflow-Inc/diffusers#26]
### when I try:

```
import os
import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    '~/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/',
    revision="fp16",
    torch_dtype=torch.float16
)
```

### Error
OSError: We couldn't connect to 'https://huggingface.co' to load this model, couldn't find it in the cached files and it looks like ~/.cache/huggingface/diffusers/models--CompVis--stable-diffusion-v1-4/ is not the path to a directory containing a model_index.json file.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/diffusers/installation#offline-mode'.

### In addition
when I try:
```
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    './stable-diffusion-v1-4',  # download from huggingface diffusers model
    revision="fp16",
    torch_dtype=torch.float16
)
```
### Error
```
RuntimeError: Error(s) in loading state_dict for OneFlowAutoencoderKL:
	While copying the parameter "encoder.conv_in.weight", an exception occurred : 

	Traceback (most recent call last):
	  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/oneflow/nn/module.py", line 788, in _load_from_state_dict
	    param.copy_(input_param)
	  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 341, in _copy
	    _copy_from_numpy_to_eager_local_tensor(self, other)
	  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 290, in _copy_from_numpy_to_eager_local_tensor
	    assert np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype(
	AssertionError
```

### System Info

- Platform: Linux-4.19.91-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.11.0 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.0.dev0
- oneflow：0.8.1+cu112.git.5610333

**Comment by jackalcooper** [comment]
@zyx1213271098 I tried to used the cached model and failed as well. It is very strange that 'https://huggingface.co/docs/diffusers/installation#offline-mode' this link actually doesn't point to anything.

> './stable-diffusion-v1-4'

this is the original diffusion model right? I think it requires running a conversion script to convert it to diffusers format. And this script doesn't work with oneflow (another thing I need to fix)

**Comment by zyx1213271098** [comment]
> @zyx1213271098 I tried to used the cached model and failed as well. It is very strange that 'https://huggingface.co/docs/diffusers/installation#offline-mode' this link actually doesn't point to anything.
> 
> > './stable-diffusion-v1-4'
> 
> this is the original diffusion model right? I think it requires running a conversion script to convert it to diffusers format. And this script doesn't work with oneflow (another thing I need to fix)

`./stable-diffusion-v1-4` is git clone from huggingface "CompVis/stable-diffusion-v1-4" repo.(thank you for your hard work)
