### ISSUE TITLE
Failed generate imgs when changed batch size

### ISSUE THREAD

**Issue by zengjie617789** [Oneflow-Inc/diffusers#264]
I meet a problem that when i set a inital batch size everthing is OK, while after changed batch size num, the aborted core dumpted error occured.
![image](https://github.com/Oneflow-Inc/diffusers/assets/25050291/b846a3cd-1d80-4e50-9544-da2b0120e920)

**Comment by jackalcooper** [comment]
could you post a minimum reproducible example please?

**Comment by zengjie617789** [comment]
I use gradio to visualize, the details is like below:
![image](https://github.com/Oneflow-Inc/diffusers/assets/25050291/ecb79072-60dc-468c-b8b0-9403928f7b2f)

![image](https://github.com/Oneflow-Inc/diffusers/assets/25050291/71435472-f757-4405-9897-c424ca0dd556)


after i change the num to 1, 

it occurs the error:
![image](https://github.com/Oneflow-Inc/diffusers/assets/25050291/4033ea6e-e0e3-45f4-9066-14f33272e19c)

**Comment by jackalcooper** [comment]
🤔️is the full error you are seeing now looks the same to the log in https://github.com/Oneflow-Inc/diffusers/pull/266

**Comment by strint** [comment]
We have supported the dynamic height and width of the input shape, but the dynamic batch size is not supported yet. We will figure out this problem in the next month.

If you need dynamic batch size for now, try to build a graph for each batch size.

**Comment by zengjie617789** [comment]
thanks the immediate  response. I solved this problem by presetting the batch size.
the inference speed is amazing.
