### ISSUE TITLE
LoRA 

### ISSUE THREAD

**Issue by xizi** [Oneflow-Inc/diffusers#288]
Does oneflow now support optimization of LoRA models？And can dynamically load and offload LoRA models？

**Comment by strint** [comment]
> Does oneflow now support optimization of LoRA models？And can dynamically load and offload LoRA models？

Yes, it's in https://github.com/Oneflow-Inc/diffusers#business-inquiry for the moment.

**Comment by strint** [comment]
LoRA example is released： https://github.com/Oneflow-Inc/diffusers/blob/d62abe2b94ab7c78853d5586ba80bf45905e31ad/examples/text_to_image_sdxl_lora.py#L9

**Comment by strint** [comment]
And https://github.com/siliconflow/onediff/tree/main/onediff_diffusers_extensions#fast-lora-loading-and-switching
