### ISSUE TITLE
Oneflow Enterprise

### ISSUE THREAD

**Issue by diagonalge** [Oneflow-Inc/diffusers#311]
Hi, I have sent an email about the oneflow enterprise. I have not been responded yet, what is the procedure to get oneflow enterprise?

**Comment by strint** [comment]
@jackalcooper

**Comment by strint** [comment]
> Hi, I have sent an email about the oneflow enterprise. I have not been responded yet, what is the procedure to get oneflow enterprise?

We have seen the email, and are working on it.

You can try the new community release:
- https://github.com/Oneflow-Inc/diffusers#performance 
- https://github.com/Oneflow-Inc/diffusers/releases/tag/0.11.0
