### ISSUE TITLE
Do you support the acceleration on P100?

### ISSUE THREAD

**Issue by Mortyzhou-Shef-BIT** [Oneflow-Inc/diffusers#33]
### Describe the bug

This is my performance of oneflow diffusers on P100 
<img width="789" alt="image" src="https://user-images.githubusercontent.com/54799259/202534790-f9d3ccff-ba21-4451-a4b9-d03b785e3aed.png">
its 1.68it/s

But my performance on official stable-diffusion, there is 2.32it/s on PLMS Sampler
<img width="803" alt="image" src="https://user-images.githubusercontent.com/54799259/202537026-f70903ed-8ac5-4229-badc-f74097df6de2.png">

Its doesn't support P100 card yet?

Thank you so much!

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-3.10.0-514.26.2.el7.x86_64-x86_64-with-glibc2.10
- Python version: 3.8.5
- PyTorch version (GPU?): 1.13.0 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.0.dev0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by jackalcooper** [comment]
Our implementation requires tensor cores on the GPU to gain acceleration.
