### ISSUE TITLE
Inconsistent with diffusers

### ISSUE THREAD

**Issue by dingjingzhen** [Oneflow-Inc/diffusers#36]
Using the same seed and code, the generated results are still not the same as huggingface diffusers and look relatively fuzzy

**Comment by prazyzheng** [comment]
> 
I thought the implementation of random function between torch and oneflow is different. So you can use torch to init your seed or generator, the results could be same.

**Comment by jackalcooper** [comment]
from what I can tell, they seems to be pretty similar
- oneflow backend
![a dog, baroque painting, beautiful detailed intricate insanely detailed octane render trending on ar-52-0](https://user-images.githubusercontent.com/5133557/205269246-e7b4091f-3ca3-4f74-918a-a1be22099a19.png)
- pytorch backend
![a dog, baroque painting, beautiful detailed intricate insanely detailed octane render trending on ar-18-0](https://user-images.githubusercontent.com/5133557/205269330-3ed83ed3-083b-4d64-8346-34a070d25d71.png)
