### ISSUE TITLE
First inference is too slow

### ISSUE THREAD

**Issue by kopyl** [Oneflow-Inc/diffusers#362]
When i first run `examples/text_to_image.py`, the first inference is slow.

I need this to use in serverless, so the speed benefit i get with Oneflow is destroyed with a huge cold start time.

Is there any way to load it faster? Maybe some sort of pre-compile the model before the runtime? Or something like this.

**Comment by strint** [comment]
Yes, The first inference took about 1 minute time to compile. 

I have seen your PR on this, it seems that you have gotten this done.

**Comment by kopyl** [comment]
@strint my first inference on RTX 4090 takes ±24 sec

**Comment by strint** [comment]
> @strint my first inference on RTX 4090 takes ±24 sec

Cool, you have a faster CPU.
