### ISSUE TITLE
运行img2img, 报错 Exception msg InferDataType Failed. Expected kFloat, but got kFloat16

### ISSUE THREAD

**Issue by xue2han** [Oneflow-Inc/diffusers#66]
### Describe the bug

OneFlowStableDiffusionImg2ImgPipeline 貌似没有适配。数据类型对不上

### Reproduction

import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline as StableDiffusionPipeline, OneFlowDPMSolverMultistepScheduler as DPMSolverMultistepScheduler, OneFlowStableDiffusionImg2ImgPipeline as StableDiffusionImg2ImgPipeline

model_id = "./stable-diffusion-2-model"
scheduler = DPMSolverMultistepScheduler.from_pretrained(model_id, subfolder="scheduler")
img2img = StableDiffusionImg2ImgPipeline.from_pretrained(model_id, scheduler=scheduler, torch_dtype=torch.float16)
img2img = img2img.to("cuda")

r = img2img(prompt="a cat", image=image, num_inference_steps=25)

### Logs

```shell
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
ERROR:root:Internal Error: Exception msg InferDataType Failed. Expected kFloat, but got kFloat16
```

### System Info

...

**Comment by xue2han** [comment]
我知道bug出在哪里了。
是vae的dtype不对。
我提交了一个mr，请合并

https://github.com/Oneflow-Inc/diffusers/pull/67

**Comment by Ldpe2G** [comment]
![image](https://user-images.githubusercontent.com/2424744/210060039-d2daac50-8938-489a-9c38-cbb13663d499.png)
@xue2han 你在这里加一句就能解决问题了

**Comment by xue2han** [comment]
> ![image](https://user-images.githubusercontent.com/2424744/210060039-d2daac50-8938-489a-9c38-cbb13663d499.png) @xue2han 你在这里加一句就能解决问题了

问题的根源是vae_oneflow.py里的代码少了几行，你可以对比下vae.py里的代码。MR在这里 #67

**Comment by Ldpe2G** [comment]
> 问题的根源是vae_oneflow.py里的代码少了几行，你可以对比下vae.py里的代码。MR在这里 #67

好的，我看到了
