### ISSUE TITLE
每次使用img2img时，unet都会重新编译

### ISSUE THREAD

**Issue by CrazyBoyM** [Oneflow-Inc/diffusers#75]
### Describe the bug

每次使用img2img时，unet都会重新编译，导致没办法投入实际使用。  
猜测是由于每次用户传入的初始图尺寸、比例不同的原因

### System Info

Oneflow + cuda11.6

**Comment by CrazyBoyM** [comment]
重新编译unet耗时太长了
```
[oneflow] a compiled unet (height=60, width=60) is deleted according to the LRU policy
[oneflow] cache size can be changed by `pipeline.set_unet_graphs_cache_size`
[oneflow] compiling unet beforehand to make sure the progress bar is more accurate
```

**Comment by Ldpe2G** [comment]
`OneFlowStableDiffusionImg2ImgPipeline` 提供了 `set_unet_graphs_cache_size` 函数，可以设置不同输入 shape unet 编译 cache 大小，比如  `pipe.set_unet_graphs_cache_size(10)` 就能 cache 10个不同的输入 shape。

**Comment by MikeHanKK** [comment]
set_unet_graphs_cache_size 非常不好用。设置了以后，GPU显存马上满了。为啥每次分辨率修改后，UNET要重新compile一次，而且还compile得那么慢啊？

**Comment by MirrorCY** [comment]
The same issue appears on the `OneFlowStableDiffusionPipeline`, where there is a long waiting when changing the image size, and cache unet quickly occupies the GPU memory, which makes the otherwise very fast oneflow diffuser unable to be used in production, what a shame

同样的问题出现在 `OneFlowStableDiffusionPipeline` 上，改变尺寸时需要等待太长的时间，而缓存 unet 会迅速占满显存，这让本来非常棒速度的 oneflow diffuser 无法投入生产使用，实在可惜

**Comment by CrazyBoyM** [comment]
是否可以采用将编译后的静态图缓存在硬盘或内存中的方案? 比如joblib这种

**Comment by jackalcooper** [comment]
> 是否可以采用将编译后的静态图缓存在硬盘或内存中的方案? 比如joblib这种

正在开发中，完成后可以只需要耗1秒就能加载一个保存在硬盘的静态图。

**Comment by MirrorCY** [comment]
太棒了，感谢~

**Comment by CrazyBoyM** [comment]
> > 是否可以采用将编译后的静态图缓存在硬盘或内存中的方案? 比如joblib这种
> 
> 正在开发中，完成后可以只需要耗1秒就能加载一个保存在硬盘的静态图。

非常棒的改进！

**Comment by strint** [comment]
## 多尺寸输入遇到的两个子问题
stable diffuison 任务在实际部署时，需要支持多 shape 的推理，当前采用了每种 shape 一个 graph 的方式来实现。一个实际用户那边需要9种输入，对应9个 graph。多个 graph 使用遇到两个问题。

问题1，常量折叠新产生的 tensor，多个 graph 间没有共享，导致多余开销。input 不同但是其它相同的每个 graph，编译都会做常量折叠，常量折叠会把和 input 无关的常量编译时计算好，这样运行时就无需计算。带来的问题是会产生新 tensor，而每个 graph 都产生自己新 tensor的话，多个 graph 之间就冗余了。

问题2, 多个 graph，上线服务时启动编译，时间比较久。用户反馈线上机器 cpu 比较弱，编译慢，希望离线编译好，线上直接加载使用。因为采用预测接口触发编译，stable diffuison unet 编译9个图（每个6.5s，共58.5s）和执行9个输入的推理，总时间约150s（在oneflow 15机器做的测评）。

## 当前新增的解决办法
对于问题1，多个 graph 共享 pass 优化后的图和常量折叠后的参数。对于stable diffuison  的 9 种 input，打开共享，可以节约近一半显存开销，每个图可以节约28%的编译时间。

对于问题2，支持离线编译，把 graph 编译后的执行计划等运行时状态保存下来，编译一次后所有线上服务加载编译结果就可使用。采用 graph 加载，stable diffuison unet 加载9个图，每个不到1s，共约8s，而之前需要150s。

以上办法**适用于在线推理的输入shape 是有限的几种的场景**，可以明显的减少显存和编译时间。适合优化那种限定几种尺寸的在线服务。

## 使用说明
这里是一个测试用例，可以先跑通来验证功能：https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py

- https://github.com/Oneflow-Inc/diffusers/pull/83#issuecomment-1413122072
- https://github.com/Oneflow-Inc/oneflow/issues/9778#issuecomment-1416901434

**Comment by Yaodada12** [comment]
> ### Describe the bug
> 每次使用img2img时，unet都会重新编译，导致没办法投入实际使用。 猜测是由于每次用户传入的初始图尺寸、比例不同的原因
> 
> ### Reproduction
> _No response_
> 
> ### Logs
> _No response_
> 
> ### System Info
> Oneflow + cuda11.6

你用的哪个模型？SD2.1还是SD2.0，可以导一份环境包给我试试吗，我这升级SD2.1模型后老跑不起来，各种bug

**Comment by strint** [comment]
> 你用的哪个模型？SD2.1还是SD2.0，可以导一份环境包给我试试吗，我这升级SD2.1模型后老跑不起来，各种bug

你可以开个 issue 专门讨论下执行错误的问题。他上面说的问题，其实是个编译性能问题，应该和你遇到的不同。

**Comment by MirrorCY** [comment]
>多尺寸输入遇到的两个子问题

Follow the steps above, I got the following results, it seems that the test did not run successfully, do I need to provide more information?
```
(base) root@c3171a95a807:/workspace# python3 diffusers/tests/test_pipelines_oneflow_graph_load.py

==> Try to run graph save...
==> get_pipe  try to run
Fetching 12 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 11394.98it/s]
get_pipe  run time  18.0778329372406
<== get_pipe  finish run

==> pipe_to_cuda  try to run
pipe_to_cuda  run time  1.3053104877471924
<== pipe_to_cuda  finish run

==> config_graph  try to run
config_graph  run time  1.6689300537109375e-05
<== config_graph  finish run

sd init time  19.383737564086914 s.
==> text_to_image  try to run
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:11<00:00,  4.36it/s]
W20230208 19:16:09.853381 23326 cudnn_conv_util.cpp:102] Currently available alogrithm (algo=1, require memory=7472256, idx=1) meeting requirments (max_workspace_size=1073741824, determinism=0) is not fastest. Fastest algorithm (1) requires memory 1074922512
text_to_image  run time  12.342012882232666
<== text_to_image  finish run

==> text_to_image  try to run
/opt/conda/lib/python3.8/site-packages/oneflow/nn/modules/module.py:152: UserWarning: Interpolate() is called in a nn.Graph, but not registered into a nn.Graph.
  warnings.warn(
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:20<00:00,  2.45it/s]
text_to_image  run time  31.601597547531128
<== text_to_image  finish run

====> diff  0.0022412804
st init and run time  63.3352324962616 s.
==> save_pipe_sch  try to run
Aborted
(base) root@c3171a95a807:/workspace# 
```

**Comment by MirrorCY** [comment]
But to be honest, I really don't understand why it's an OOM error
```
ubuntu@DESKTOP-531RKJN:~$ python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
libibverbs not available, ibv_fork_init skipped

==> Try to run graph save...
==> get_pipe  try to run
Fetching 12 files: 100%|█████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 67468.70it/s]get_pipe  run time  13.683996438980103
<== get_pipe  finish run

==> pipe_to_cuda  try to run
pipe_to_cuda  run time  2.004014492034912
<== pipe_to_cuda  finish run

==> config_graph  try to run
config_graph  run time  1.4543533325195312e-05
<== config_graph  finish run

sd init time  15.688611507415771 s.
==> text_to_image  try to run
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.47it/s]W20230209 04:59:49.699352    55 cudnn_conv_util.cpp:102] Currently available alogrithm (algo=1, require memory=7472256, idx=1) meeting requirments (max_workspace_size=1073741824, determinism=0) is not fastest. Fastest algorithm (1) requires memory 1074922512
text_to_image  run time  9.806789636611938
<== text_to_image  finish run

==> text_to_image  try to run
/home/ubuntu/.local/lib/python3.8/site-packages/oneflow/nn/modules/module.py:152: UserWarning: Interpolate() is called in a nn.Graph, but not registered into a nn.Graph.
  warnings.warn(
100%|███████████████████████████████████████████████████████████████████████████████████| 50/50 [00:16<00:00,  3.08it/s]text_to_image  run time  23.932280778884888
<== text_to_image  finish run

====> diff  0.0018569464
st init and run time  49.43372464179993 s.
==> save_pipe_sch  try to run
terminate called after throwing an instance of 'oneflow::RuntimeException'
  what():  Error: out of memory
You can set ONEFLOW_DEBUG or ONEFLOW_PYTHON_STACK_GETTER to 1 to get the Python stack of the error.
Aborted
ubuntu@DESKTOP-531RKJN:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           62Gi       365Mi        57Gi       2.0Mi       4.7Gi        61Gi
Swap:          16Gi          0B        16Gi
ubuntu@DESKTOP-531RKJN:~$ nvidia-smi
Thu Feb  9 05:01:26 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.05    Driver Version: 528.24       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:2B:00.0  On |                  N/A |
|  0%   34C    P8    25W / 350W |   1000MiB / 24576MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        23      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+
ubuntu@DESKTOP-531RKJN:~$
```

**Comment by strint** [comment]
> ==> save_pipe_sch  try to run
> what():  Error: out of memory

In our test, it needs less than 12 G  cuda memory.  The out of memory error at saving is unexpected.

You can get cuda mem log by update _cost_cnt at https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py#L21
```
def _cost_cnt(fn):
    def new_fn(*args, **kwargs):
        print("==>", fn.__name__, " try to run")
        flow._oneflow_internal.eager.Sync()
        before_used = flow._oneflow_internal.GetCUDAMemoryUsed()
        print(fn.__name__, " cuda mem before ",  before_used)
        start_time = time.time()
        out = fn(*args, **kwargs)
        flow._oneflow_internal.eager.Sync()
        end_time = time.time()
        print(fn.__name__, " run time ", end_time - start_time)
        after_used = flow._oneflow_internal.GetCUDAMemoryUsed()
        print(fn.__name__, " cuda mem after ", after_used)
        print(fn.__name__, " cuda mem diff ", after_used - before_used)
        print("<==", fn.__name__, " finish run")
        print("")
        return out

    return new_fn
```

Let's see what the mem log tells us.

@MirrorCY 

By the way, is the cuda memory has other users ?

**Comment by MirrorCY** [comment]
@strint Thank you for your quick reply! The running environment is wsl2 Ubuntu 20.04, neither the host nor wsl2 is running any other CUDA programs.
```
ubuntu@DESKTOP-531RKJN:~$ python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
libibverbs not available, ibv_fork_init skipped

==> Try to run graph save...
==> get_pipe  try to run
get_pipe  cuda mem before  1301.5
Fetching 12 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 56488.94it/s]
get_pipe  run time  15.074813842773438
get_pipe  cuda mem after  1301.5
get_pipe  cuda mem diff  0.0
<== get_pipe  finish run

==> pipe_to_cuda  try to run
pipe_to_cuda  cuda mem before  1301.5
pipe_to_cuda  run time  1.1066811084747314
pipe_to_cuda  cuda mem after  4061.5
pipe_to_cuda  cuda mem diff  2760.0
<== pipe_to_cuda  finish run

==> config_graph  try to run
config_graph  cuda mem before  4061.5
config_graph  run time  1.5735626220703125e-05
config_graph  cuda mem after  4061.5
config_graph  cuda mem diff  0.0
<== config_graph  finish run

sd init time  16.18261170387268 s.
==> text_to_image  try to run
text_to_image  cuda mem before  4061.5
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:09<00:00,  5.53it/s]
W20230210 00:32:48.454388  8336 cudnn_conv_util.cpp:102] Currently available alogrithm (algo=1, require memory=7472256, idx=1) meeting requirments (max_workspace_size=1073741824, determinism=0) is not fastest. Fastest algorithm (1) requires memory 1074922512
text_to_image  run time  9.699114561080933
text_to_image  cuda mem after  8125.5
text_to_image  cuda mem diff  4064.0
<== text_to_image  finish run

==> text_to_image  try to run
text_to_image  cuda mem before  8125.5
/home/ubuntu/.local/lib/python3.8/site-packages/oneflow/nn/modules/module.py:152: UserWarning: Interpolate() is called in a nn.Graph, but not registered into a nn.Graph.
  warnings.warn(
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:15<00:00,  3.17it/s]
text_to_image  run time  23.669822216033936
text_to_image  cuda mem after  9561.5
text_to_image  cuda mem diff  1436.0
<== text_to_image  finish run

====> diff  0.0023254268
st init and run time  49.55777668952942 s.
==> save_pipe_sch  try to run
save_pipe_sch  cuda mem before  9561.5
terminate called after throwing an instance of 'oneflow::RuntimeException'
  what():  Error: out of memory
Error message from /home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp:209
        OpCallInstructionUtil::Compute(this, instruction): copy:OpCall:s_d2h

  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 209, in Compute
    OpCallInstructionUtil::Compute(this, instruction)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 41, in Compute
    AllocateOutputBlobsMemory(op_call_instruction_policy, allocator, instruction)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 89, in AllocateOutputBlobsMemory
    blob_object->TryAllocateBlobBodyMemory(allocator)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/eager/eager_blob_object.cpp", line 100, in TryAllocateBlobBodyMemory
    allocator->Allocate(&dptr, required_body_bytes)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 392, in Allocate
    AllocateBlockToExtendTotalMem(aligned_size)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/bin_allocator.h", line 305, in AllocateBlockToExtendTotalMem
    backend_->Allocate(&mem_ptr, final_allocate_bytes)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/ep_backend_host_allocator.cpp", line 25, in Allocate
    ep_device_->AllocPinned(allocation_options_, reinterpret_cast<void**>(mem_ptr), size)
Error Type: oneflow.ErrorProto.runtime_error
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/vm/op_call_instruction_policy.cpp", line 209, in operator()
    
Error Type: oneflow.ErrorProto.runtime_error
You can set ONEFLOW_DEBUG or ONEFLOW_PYTHON_STACK_GETTER to 1 to get the Python stack of the error.
Aborted
ubuntu@DESKTOP-531RKJN:~$ 
```

**Comment by strint** [comment]
> save_pipe_sch  cuda mem before  9561.5 

Here only takes 9.5 G cuda memory.  Do you observe the OOM in nvidia-smi?

@MirrorCY

**Comment by MirrorCY** [comment]
I quickly took a screenshot, but didn't find any OOM occurring.
![image](https://user-images.githubusercontent.com/37006258/217889472-7a6b9f75-3504-4fce-aa14-bca11fac2080.png)

**Comment by MirrorCY** [comment]
```
ubuntu@DESKTOP-531RKJN:~$ python3 -m oneflow --doctor
libibverbs not available, ibv_fork_init skipped
path: ['/home/ubuntu/.local/lib/python3.8/site-packages/oneflow']
version: 0.9.1.dev20230208+cu117
git_commit: 0cc4a56b
cmake_build_type: Release
rdma: True
mlir: True
```

**Comment by strint** [comment]
> I quickly took a screenshot, but didn't find any OOM occurring. ![image](https://user-images.githubusercontent.com/37006258/217889472-7a6b9f75-3504-4fce-aa14-bca11fac2080.png)

It seems that it is out of your host ( CPU ) memory, please check this.

**Comment by MirrorCY** [comment]
https://github.com/Oneflow-Inc/diffusers/issues/75#issuecomment-1423233889
> ubuntu@DESKTOP-531RKJN:~$ free -h
              total        used        free      shared  buff/cache   available
Mem:           62Gi       365Mi        57Gi       2.0Mi       4.7Gi        61Gi
Swap:          16Gi          0B        16Gi

**Comment by strint** [comment]
> > ubuntu@DESKTOP-531RKJN:~$ free -h
> > total        used        free      shared  buff/cache   available
> > Mem:           62Gi       365Mi        57Gi       2.0Mi       4.7Gi        61Gi
> > Swap:          16Gi          0B        16Gi

Do you run ubuntu in a vm ? Maybe your need to increase the memory of you VM for the ubuntu.
@MirrorCY

**Comment by MirrorCY** [comment]
It is in wsl2 Ubuntu 20.04, host is Windows 10
```
[wsl2]
memory=64GB
swap=64GB
localhostForwarding=true
```

**Comment by strint** [comment]
> It is in wsl2 Ubuntu 20.04, host is Windows 10 Both `free -h` and Oneflow are running in WSL2
> 
> ```
> [wsl2]
> memory=64GB
> swap=64GB
> localhostForwarding=true
> ```

`I have 32 GB available in Windows, but WSL2 is only allowing me to use up to 24 of that. `  [Reference](https://superuser.com/questions/1707758/wsl-2-does-not-have-all-memory-available-to-it#:~:text=If%20you%20need%20more%20memory,80%25%20on%20builds%20before%2020175.)

You can use `top` in you wsl ubuntu to check the usage of CPU memory.

@MirrorCY

**Comment by MirrorCY** [comment]
> You can use top in you wsl ubuntu to check the usage of CPU memory.

![image](https://user-images.githubusercontent.com/37006258/217899080-d8706bab-ff19-4bce-8f57-e032536e29dd.png)

**Comment by MirrorCY** [comment]
要我不加群说，似乎这个问题在此处被拉的太长了，而且参考价值不算太大

**Comment by strint** [comment]
> 要我不加群说，似乎这个问题在此处被拉的太长了，而且参考价值不算太大

可以的，我的 QQ 545991660

@MirrorCY

**Comment by MirrorCY** [comment]
一个反馈，我直接在生产环境加上了 `pipe.enable_graph_share_mem()`，它工作的很棒。 🚀

**Comment by strint** [comment]
> 一个反馈，我直接在生产环境加上了 `pipe.enable_graph_share_mem()`，它工作的很棒。 🚀

赞，enable_graph_share_mem 相关的策略主要可以节约（自测的场景有40%+）显存 和 20%+的编译时间。

load_graph 主要是可以避免上线时的编译时间。

**Comment by strint** [comment]
@MirrorCY 你那边生产环境部署，会约定几种有限的图片尺寸么，还是是任意的 @MirrorCY

**Comment by MirrorCY** [comment]
> 会约定几种有限的图片尺寸么，还是是任意的

接近任意的，短边 512，长边最大 2048，步进 128
顺便想问问 set_graph_compile_cache_size() 是怎么样的过期策略，最后缓存的直接挤走最先缓存的吗

**Comment by strint** [comment]
> > 会约定几种有限的图片尺寸么，还是是任意的
> 
> 接近任意的，短边 512，长边最大 2048，步进 128 顺便想问问 set_graph_compile_cache_size() 是怎么样的过期策略，最后缓存的直接挤走最先缓存的吗

是的，一个 LRU 策略。实现在这里：https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/src/diffusers/oneflow_graph_compile_cache.py#L66

**Comment by MirrorCY** [comment]
好棒！很符合我对缓存的队列的想象（

**Comment by Nipi64310** [comment]
Hi @strint ，
我安装你[上边](https://github.com/Oneflow-Inc/diffusers/issues/75#issuecomment-1418789541)写的在容器内重新安装了oneflow和diffusers
执行测试文件报错如下，请问这是没有更新成功吗？

```
root@5479876cb7f9:/diffusers# python -u tests/test_pipelines_oneflow_graph_load.py 

==> Try to run graph save...
==> function  get_pipe  try to run...
get_pipe  cuda mem before  103.0  MB
get_pipe  host mem before  566.0  MB
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
The config attributes {'upcast_attention': True} were passed to OneFlowUNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
get_pipe  run time  21.65649437904358  seconds
get_pipe  cuda mem after  103.0  MB
get_pipe  cuda mem diff  0.0  MB
get_pipe  host mem after  5487.0  MB
get_pipe  host mem diff  4921.0  MB
<== function  get_pipe  finish run.

==> function  pipe_to_cuda  try to run...
pipe_to_cuda  cuda mem before  103.0  MB
pipe_to_cuda  host mem before  5487.0  MB
pipe_to_cuda  run time  0.6609971523284912  seconds
pipe_to_cuda  cuda mem after  2891.0  MB
pipe_to_cuda  cuda mem diff  2788.0  MB
pipe_to_cuda  host mem after  5508.0  MB
pipe_to_cuda  host mem diff  21.0  MB
<== function  pipe_to_cuda  finish run.

==> function  config_graph  try to run...
config_graph  cuda mem before  2891.0  MB
config_graph  host mem before  5508.0  MB
config_graph  run time  4.458427429199219e-05  seconds
config_graph  cuda mem after  2891.0  MB
config_graph  cuda mem diff  0.0  MB
config_graph  host mem after  5508.0  MB
config_graph  host mem diff  0.0  MB
<== function  config_graph  finish run.

sd init time  22.321678638458252 s.
==> function  text_to_image  try to run...
text_to_image  cuda mem before  2891.0  MB
text_to_image  host mem before  5508.0  MB
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:31<00:00,  1.61it/s]
W20230210 06:40:09.136538  4109 cudnn_conv_util.cpp:102] Currently available alogrithm (algo=1, require memory=7472256, idx=2) meeting requirments (max_workspace_size=1073741824, determinism=0) is not fastest. Fastest algorithm (1) requires memory 1074922512
text_to_image  run time  32.99919414520264  seconds
text_to_image  cuda mem after  6843.0  MB
text_to_image  cuda mem diff  3952.0  MB
text_to_image  host mem after  6052.0  MB
text_to_image  host mem diff  544.0  MB
<== function  text_to_image  finish run.

==> function  text_to_image  try to run...
text_to_image  cuda mem before  6843.0  MB
text_to_image  host mem before  6052.0  MB
E
======================================================================
ERROR: test_sd_graph_save_and_load (__main__.OneFlowPipeLineGraphSaveLoadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_pipelines_oneflow_graph_load.py", line 180, in test_sd_graph_save_and_load
    _test_sd_graph_save_and_load(True, f0 ,f1, f2)
  File "tests/test_pipelines_oneflow_graph_load.py", line 147, in _test_sd_graph_save_and_load
    with_g_images = text_to_image(prompt, (i, j), prefix=f"is_save_{str(is_save)}-", with_graph=True)
  File "tests/test_pipelines_oneflow_graph_load.py", line 30, in new_fn
    out = fn(*args, **kwargs)
  File "tests/test_pipelines_oneflow_graph_load.py", line 122, in text_to_image
    images = pipe(
  File "/oneflow/python/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 653, in __call__
    unet_graph = self.graph_compile_cache.get_graph(UNetGraph, cache_key, self.unet)
  File "/diffusers/src/diffusers/oneflow_graph_compile_cache.py", line 194, in get_graph
    graph.graph_.enable_save_runtime_state_dict()
  File "/oneflow/python/oneflow/nn/graph/graph.py", line 1417, in __getattr__
    raise AttributeError(
AttributeError: 'UNetGraph' object has no attribute 'enable_save_runtime_state_dict'

----------------------------------------------------------------------
Ran 1 test in 55.644s

FAILED (errors=1)
```

**Comment by strint** [comment]
> AttributeError: 'UNetGraph' object has no attribute 'enable_save_runtime_state_dict'
> 
> ----------------------------------------------------------------------
> Ran 1 test in 55.644s
> 
> FAILED (errors=1)
> ```

看起来像是 oneflow 版本没有更新到最新。用这个看下 oneflow 版本：
```
python3 -m oneflow --doctor
```

**Comment by Nipi64310** [comment]
> python3 -m oneflow --doctor

感谢回复，
```
root@5479876cb7f9:/app# python3 -m oneflow --doctor
path: ['/oneflow/python/oneflow']
version: 0.9.1+cu118.git.7f6122c767
git_commit: 7f6122c767
cmake_build_type: Release
rdma: False
mlir: True
```

**Comment by strint** [comment]
> > python3 -m oneflow --doctor
> 
> 感谢回复，
> 
> ```
> root@5479876cb7f9:/app# python3 -m oneflow --doctor
> path: ['/oneflow/python/oneflow']
> version: 0.9.1+cu118.git.7f6122c767
> git_commit: 7f6122c767
> cmake_build_type: Release
> rdma: False
> mlir: True
> ```

这个功能是新增的，所以你需要 update oneflow 一下，参考这里：https://github.com/Oneflow-Inc/diffusers/issues/75#issuecomment-1418789541

**Comment by CrazyBoyM** [comment]
可以在Oneflow-Inc/diffusers/doc补充一份针对这方面场景的文档么？

**Comment by strint** [comment]
> 可以在Oneflow-Inc/diffusers/doc补充一份针对这方面场景的文档么？

@doombeaker 这个一般是加在哪里比较好呢

**Comment by strint** [comment]
> 可以在Oneflow-Inc/diffusers/doc补充一份针对这方面场景的文档么？

https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion#optimization-for-multi-resolution-picture

@CrazyBoyM

**Comment by doombeaker** [comment]
> > 可以在Oneflow-Inc/diffusers/doc补充一份针对这方面场景的文档么？
> 
> @doombeaker 这个一般是加在哪里比较好呢

仓库的 wiki 里吧。现在 oneflow-sd 相关的资料其实都是在 wiki 里。保持信息集中。

**Comment by strint** [comment]
> > > 可以在Oneflow-Inc/diffusers/doc补充一份针对这方面场景的文档么？
> > 
> > 
> > @doombeaker 这个一般是加在哪里比较好呢
> 
> 仓库的 wiki 里吧。现在 oneflow-sd 相关的资料其实都是在 wiki 里。保持信息集中。

好的，已经加到 wiki

**Comment by jackalcooper** [comment]
looks like it has been resolved, feel free to reopen if not.

**Comment by Amber0130** [comment]
> python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
你好，复现这个时候出现以下错误，麻烦问一下是怎么回事呀
<img width="960" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/a98a6902-c623-4907-b362-60d04e4aa372">

<img width="1138" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/28805300-1ec7-46c5-a3cd-639e83839b6b">

**Comment by jackalcooper** [comment]
@strint 👀

**Comment by strint** [comment]
> > python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
> > 你好，复现这个时候出现以下错误，麻烦问一下是怎么回事呀
> 
> <img alt="image" width="960" src="https://user-images.githubusercontent.com/54001386/259041393-a98a6902-c623-4907-b362-60d04e4aa372.png"> 

看起来这里有个循环依赖问题，你的 python 版本是多少呢

**Comment by Amber0130** [comment]
> > > python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
> > > 你好，复现这个时候出现以下错误，麻烦问一下是怎么回事呀
> > 
> > 
> > <img alt="image" width="960" src="https://user-images.githubusercontent.com/54001386/259041393-a98a6902-c623-4907-b362-60d04e4aa372.png">
> 
> 看起来这里有个循环依赖问题，你的 python 版本是多少呢

Python 3.10.12

**Comment by strint** [comment]
> > python3 -m pip install -e .[oneflow]
> 
> 谢谢，这个问题解决了 在生成不同size图片的时候出现以下日志 <img alt="image" width="962" src="https://user-images.githubusercontent.com/54001386/259052616-1e0abe00-76cc-4422-9b91-a52ca96c7746.png">
> 
> <img alt="image" width="1402" src="https://user-images.githubusercontent.com/54001386/259052541-f55ff160-2499-4f28-ba99-614eb1d80139.png">

这个提示信息不影响正确性，请暂时忽略，我们这两天会 fix 这个 warning。

**Comment by Amber0130** [comment]
> > python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
> 
> 你这个代码看起来是很老的一个版本，使用下最新的看看：https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py

你好，这个已经复现成功，但是我改变了图片大小，图片大小的列表为size_config = [[752,1000],[720,1280],[800,448],[448,800],[448,600],[600,448],[400,600],[600,400],[480,480]]，发现生成第二张图片时候报一下错误

<img width="1221" alt="image" src="https://github.com/Oneflow-Inc/diffusers/assets/54001386/cdbf4f9b-d388-4fec-878f-4bb18db3c896">

**Comment by Amber0130** [comment]
> > > python3 diffusers/tests/test_pipelines_oneflow_graph_load.py
> > 
> > 
> > 你这个代码看起来是很老的一个版本，使用下最新的看看：https://github.com/Oneflow-Inc/diffusers/blob/main/examples/text_to_image_graph_load.py
> 
> 你好，这个已经复现成功，但是我改变了图片大小，图片大小的列表为size_config = [[752,1000],[720,1280],[800,448],[448,800],[448,600],[600,448],[400,600],[600,400],[480,480]]，发现生成第二张图片时候报一下错误
> 
> <img alt="image" width="1221" src="https://user-images.githubusercontent.com/54001386/259113497-cdbf4f9b-d388-4fec-878f-4bb18db3c896.png">

@strint 你好，oneflow多个图片大小编译的时候有什么要注意的嘛？
