### ISSUE TITLE
not working with xformers?

### ISSUE THREAD

**Issue by MikeHanKK** [Oneflow-Inc/diffusers#80]
### Describe the bug

all kinds of problems, depending on which versions of xformers installed. I tried the master dev branch, v0.0.13, v0.0.12. All had some exceptions. I believe the main problem is the system cannot cast verify the inputs with oneflow.float32 while it should be torch.float32. Which version of xformers is the current dev version of oneflow is testing against?

### System Info

python3.10, cu117, the latest oneflow version.

**Comment by jackalcooper** [comment]
oneflow has CUDA kernels built-in with similar optimization as xformers, so it is not necessary
