### ISSUE TITLE
run  by  "How to Run OneFlow Stable Diffusion "

### ISSUE THREAD

**Issue by liuchenbaidu** [Oneflow-Inc/diffusers#85]
### Describe the bug

oneflow.cuda.amp.GradScaler is not implemented, please submit an issue at
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the
minimum reproduction code, and the system information.

### System Info

Unbunt RTX3090

**Comment by strint** [comment]
Close with https://github.com/Oneflow-Inc/oneflow/issues/9822
