### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'mock_torch'

### ISSUE THREAD

**Issue by JioChoi** [Oneflow-Inc/diffusers#87]
### Describe the bug

I got an error while following https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion.

### Logs

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-32-9857761ca7ed>](https://localhost:8080/#) in <module>
      2 from diffusers import OneFlowStableDiffusionPipeline
      3 
----> 4 pipe = OneFlowStableDiffusionPipeline.from_pretrained(
      5     "CompVis/stable-diffusion-v1-4",
      6     use_auth_token=True,

[/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_oneflow_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    714                 class_candidates = {c: class_obj for c in importable_classes.keys()}
    715             else:
--> 716                 with torch.mock_torch.enable():
    717                     # else we just import it from the library.
    718                     library = importlib.import_module(library_name)

AttributeError: module 'torch' has no attribute 'mock_torch'
```

### System Info

Colab.
Tried almost every versions untill 0.7.0dev0.

- `diffusers` version: 0.7.0.dev0
- Platform: Linux-5.10.147+-x86_64-with-glibc2.29
- Python version: 3.8.10
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- Huggingface_hub version: 0.12.0
- Transformers version: 4.26.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by daquexian** [comment]
Thanks for your issue! Could you please install the latest oneflow following https://github.com/Oneflow-Inc/oneflow#install-with-pip-package?

**Comment by JioChoi** [comment]
> Thanks for your issue! Could you please install the latest oneflow following https://github.com/Oneflow-Inc/oneflow#install-with-pip-package?

ImportError                               Traceback (most recent call last)

<ipython-input-14-9857761ca7ed> in <module>
      1 import oneflow as torch
----> 2 from diffusers import OneFlowStableDiffusionPipeline
      3 
      4 pipe = OneFlowStableDiffusionPipeline.from_pretrained(
      5     "CompVis/stable-diffusion-v1-4",

ImportError: cannot import name 'OneFlowStableDiffusionPipeline' from 'diffusers' (unknown location)

I got another error.

**Comment by daquexian** [comment]
You seem to use huggingface/diffusers rather than Oneflow-Inc/diffusers. Please check if you follow all instructions in https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion

**Comment by JioChoi** [comment]
> You seem to use huggingface/diffusers rather than Oneflow-Inc/diffusers. Please check if you follow all instructions in https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion

I exactly followed this one but somehow not working.
Did I do something wrong?
![Screenshot_20230206_174740_Firefox Nightly.png](https://user-images.githubusercontent.com/73428860/216926136-8a399173-6d1b-4999-8106-dd5fef88ff8d.png)

**Comment by daquexian** [comment]
I noticed that you installed oneflow for three times (No.3 - No.5 commands in your screenshot). Could you please try again and install oneflow by only this one command: `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117`?

**Comment by JioChoi** [comment]
> I noticed that you installed oneflow for three times (No.3 - No.5 commands in your screenshot). Could you please try again and install oneflow by only this one command: `python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/master/cu117`

![Screenshot_20230206_194743_Firefox Nightly.png](https://user-images.githubusercontent.com/73428860/216952497-15e8c4a7-2ba7-4d05-97e0-a4906785b3c6.png)
Still getting same error.

**Comment by daquexian** [comment]
After investigation, I found the problem comes from IPython and editable installation (i.e. `pip install -e`): https://stackoverflow.com/questions/57838013/modulenotfounderror-after-successful-pip-install-in-google-colaboratory. 

Please restart the colab notebook after installing diffusers, or replace `pip install -e` with plain `pip install`.

**Comment by yuanms2** [comment]
> After investigation, I found the problem comes from IPython and editable installation (i.e. `pip install -e`): https://stackoverflow.com/questions/57838013/modulenotfounderror-after-successful-pip-install-in-google-colaboratory.
> 
> Please restart the colab notebook after installing diffusers, or replace `pip install -e` with plain `pip install`.

@jackalcooper 
We should correct the README at: https://github.com/Oneflow-Inc/diffusers/wiki/How-to-Run-OneFlow-Stable-Diffusion
