### ISSUE TITLE
No module named 'oneflow.utils.checkpoint'

### ISSUE THREAD

**Issue by qiuyanxin** [Oneflow-Inc/diffusers#9]
### Describe the bug

  File "/root/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 6, in <module>
    import oneflow.utils.checkpoint

### Reproduction

import oneflow as torch
from diffusers import OneFlowStableDiffusionPipeline
pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    local_model_path,
    use_auth_token=True,
    revision="fp16",
    torch_dtype=torch.float16,
)

### Logs

```shell
Traceback (most recent call last):
  File "demo_inference.py", line 8, in <module>
    from diffusers import StableDiffusionPipeline
  File "/root/diffusers/src/diffusers/__init__.py", line 21, in <module>
    from .models import AutoencoderKL, UNet2DConditionModel, UNet2DModel, VQModel
  File "/root/diffusers/src/diffusers/models/__init__.py", line 28, in <module>
    from .unet_2d_condition_oneflow import OneFlowUNet2DConditionModel
  File "/root/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 6, in <module>
    import oneflow.utils.checkpoint
ModuleNotFoundError: No module named 'oneflow.utils.checkpoint'
```

### System Info

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)
[GCC 7.5.0]
OS platform: Linux-4.19.0-19-amd64-x86_64-with-glibc2.17
OS architecture: x86_64
Torch version: 1.12.1+cu102
Cuda available: True
Cuda version: 10.2
CuDNN version: 7605
Number of GPUs available: 1
transformers version: 4.23.0.dev0

**Comment by jackalcooper** [comment]
Did you install the stable version 0.8.0 of OneFlow? It might have some problems. Try this
```
python3 -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
python3 -m pip install --pre oneflow -f https://staging.oneflow.info/branch/release/debug-sd-conv-gn-geglu/cu112
```

**Comment by zyx1213271098** [comment]
需要0.8.1版本的oneflow

**Comment by xiaohaipeng** [comment]
有0.8.1的oneflow？

**Comment by qiuyanxin** [comment]
> @qiuyanxin how did you solve this problem?
I did not solve the problem. According to [jackalcooper](https://github.com/jackalcooper) I installed oneflow==0.8.1, but I got an assertion error like this  assert 'np_arr.dtype == flow.convert_oneflow_dtype_to_numpy_dtype' @jackalcooper
