### ISSUE TITLE
sd2是否支持多卡推理？

### ISSUE THREAD

**Issue by Nipi64310** [Oneflow-Inc/diffusers#91]
Hi 
感谢开源，在t4卡上，对比了下Aitempleate和oneflow，oneflow效果上比较稳定，但是虽然优化提速了很多，单条prompt生成(768*768,  steps=20)差不多还是要5s，可以通过多卡来提升性能吗？

**Comment by jackalcooper** [comment]
目前比较流行的是用多进程来加速

**Comment by Nipi64310** [comment]
> 目前比较流行的是用多进程来加速

Hello @jackalcooper ，
感谢回复，多进程加速是类似[这种](https://github.com/NickLucche/stable-diffusion-nvidia-docker#data-parallel)吗

**Comment by jackalcooper** [comment]
> > 目前比较流行的是用多进程来加速
> 
> Hello @jackalcooper ，
> 感谢回复，多进程加速是类似[这种](https://github.com/NickLucche/stable-diffusion-nvidia-docker#data-parallel)吗

这个看上去是数据并行了，我的意思是如果只是想加速生成多张图片，开多个进程来生成图片

**Comment by Nipi64310** [comment]
> 

那单张图片的生成速度能通过多卡来提升吗

**Comment by jackalcooper** [comment]
> > 
> 
> 那单张图片的生成速度能通过多卡来提升吗

理论上是可以的，因为一张图的prompt实际上会产生两个噪声，一个会被prompt影响，一个不会

**Comment by xyfZzz** [comment]
> > > 目前比较流行的是用多进程来加速
> > 
> > 
> > Hello @jackalcooper ，
> > 感谢回复，多进程加速是类似[这种](https://github.com/NickLucche/stable-diffusion-nvidia-docker#data-parallel)吗
> 
> 这个看上去是数据并行了，我的意思是如果只是想加速生成多张图片，开多个进程来生成图片

请问数据并行是开多个进程来生成图片吗？另外请问怎么开多个进程来生成图片？
