### ISSUE TITLE
[Performance Issue]:  Takes a long time after a change in width and height to previous request

### ISSUE THREAD

**Issue by diagonalge** [Oneflow-Inc/diffusers#98]
### Brief Description

I am using oneflow with stable diffusion. If I generate the results in 512x512, it can generate the result in 1 second. If I change the width and height, it will generate the next result in ~10 seconds. Then it will generate normally afterwards on the same dimensions. So, a change in width and height causes the model to slow down for the first inference on the new dimensions.

### Device and Context

A100 40 Gb.

### Benchmark

Normal inference: ~1 second
Inference after change in dimensions (for first time): ~10 seconds

**Comment by jackalcooper** [comment]
looks like it has been resolved, feel free to reopen if not.
